// Travel-ID i18n catalog
// Languages: en (default), id (Bahasa Indonesia), ko (한국어), zh-CN (简体中文), ja (日本語)
// Categories: beach, temple, cultural, volcano, nature, diving, food, cafe, shopping,
//             nightlife, mosque, museum, adventure, wellness
// Regions: Bali, Jakarta, Yogyakarta, Bandung, Lombok, Komodo, Surabaya, Medan,
//          Bromo, Borobudur, Raja Ampat, Sumatra, Sulawesi, Kalimantan, Other

const translations = {
  en: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — Discover Indonesia | Beyond Bali Travel Guide",
    "seo.description": "Discover the best travel spots in Indonesia recommended by the community. Bali, Yogyakarta, Komodo, Bromo, Raja Ampat and beyond — with halal food, prayer rooms, and AI trip planning.",
    "seo.keywords": "Indonesia travel, Bali travel guide, Yogyakarta tour, Borobudur, Komodo dragon, Mt Bromo, Raja Ampat, Lombok, Indonesia trip planner, halal food Bali, Muslim friendly Indonesia, Indonesia attractions, things to do Indonesia, Indonesia map, Java travel, Sumatra travel, Sulawesi travel",

    "nav.home": "Home",
    "nav.explore": "Explore",
    "nav.lang": "Bahasa",

    "app.title": "Discover Indonesia",
    "app.subtitle": "Travel spots recommended by the community",
    "app.searchPh": "Search places...",
    "app.catAll": "All",
    "app.catBeach": "Beach",
    "app.catTemple": "Temple",
    "app.catCultural": "Cultural",
    "app.catVolcano": "Volcano",
    "app.catNature": "Nature",
    "app.catDiving": "Diving",
    "app.catFood": "Food",
    "app.catCafe": "Cafe",
    "app.catShopping": "Shopping",
    "app.catNightlife": "Nightlife",
    "app.catMuseum": "Museum",
    "app.catAdventure": "Adventure",
    "app.catWellness": "Wellness",
    "app.catHalal": "Halal Food",
    "app.catMosque": "Mosque / Prayer Room",
    "app.catVegetarian": "Vegetarian",
    "app.muslimToggle": "Muslim Friendly",
    "app.muslimDesc": "+ Halal restaurants & prayer rooms (musholla) included",

    "prefs.title": "Travel Settings",
    "prefs.dietary": "Preferences",
    "prefs.muslim": "Muslim Friendly",
    "prefs.vegan": "Vegan",
    "prefs.visitType": "Visit Type",
    "prefs.local": "Local Resident",
    "prefs.firstVisit": "First Visit (international)",
    "prefs.returnVisit": "Return Visit (international)",
    "prefs.business": "Business Trip",
    "prefs.group": "Group Travel",
    "prefs.apply": "Apply",

    "guide.btn": "How to Use",
    "guide.title": "How to Use Travel-ID",
    "guide.step1Title": "Browse Spots",
    "guide.step1Desc": "Explore travel spots across Indonesia recommended by fellow travelers. Filter by category (Beach, Temple, Volcano, etc.) and region (Bali, Yogyakarta, Komodo, …).",
    "guide.step2Title": "Travel Settings",
    "guide.step2Desc": "Tap the gear icon to set your dietary preferences (Muslim Friendly, Vegan) and visit type. These shape what shows on the map and what the AI planner recommends.",
    "guide.step3Title": "View Spot Details",
    "guide.step3Desc": "Tap any spot to see photos, description, address, halal/prayer room flags, and entry fees. Open directions in Google Maps with one tap.",
    "guide.step4Title": "Switch Map & List",
    "guide.step4Desc": "On mobile, use the Map/List button at the bottom. On desktop, both views are shown side by side.",
    "guide.step5Title": "Save & Bookmark",
    "guide.step5Desc": "Sign in with Google to bookmark spots as 'Want to Visit' or 'Interested'. Saved spots appear in the My Spots tab and feed the AI planner.",
    "guide.step6Title": "AI Trip Planner",
    "guide.step6Desc": "After saving spots, open Plan Trip from the menu. Pick duration, budget, and style — the AI builds a day-by-day itinerary including inter-island transport (ferry / domestic flight) and meal suggestions.",
    "guide.dontShowAgain": "Don't show again",
    "guide.dontShowToday": "Don't show today",

    "about.btn": "About",
    "about.title": "About Travel-ID",
    "about.privacy": "Privacy Policy",
    "about.terms": "Terms of Service",
    "about.koinfo": "",

    "app.viewMap": "Map",
    "app.viewList": "List",
    "app.regionAll": "All Regions",
    "app.regionBali": "Bali",
    "app.regionJakarta": "Jakarta",
    "app.regionYogyakarta": "Yogyakarta",
    "app.regionBandung": "Bandung",
    "app.regionLombok": "Lombok",
    "app.regionKomodo": "Komodo",
    "app.regionSurabaya": "Surabaya",
    "app.regionMedan": "Medan",
    "app.regionBromo": "Bromo",
    "app.regionBorobudur": "Borobudur",
    "app.regionRajaAmpat": "Raja Ampat",
    "app.regionSumatra": "Sumatra",
    "app.regionSulawesi": "Sulawesi",
    "app.regionKalimantan": "Kalimantan",
    "app.regionOther": "Other",

    "app.featured": "Featured",
    "app.rating": "Rating",
    "app.views": "Views",
    "app.noResults": "No spots found. Try a different filter.",
    "app.loading": "Loading spots...",
    "app.loadMore": "Load More",
    "app.openGoogle": "Open in Google Maps",
    "app.mapGoogle": "Google Maps",
    "app.website": "Official Website",
    "app.openingHours": "Opening Hours",
    "app.entryFee": "Entry Fee",
    "app.entryFeeFree": "Free",
    "app.bestTime": "Best Time to Visit",
    "app.localTips": "Local Tips",
    "app.halalBadge": "Halal",
    "app.prayerRoomBadge": "Prayer Room",
    "app.checkBusy": "Check busy times on Google Maps",
    "app.shareSpot": "Share a Spot",
    "app.submitTitle": "Share an Indonesia Travel Spot",
    "app.submitNotice": "Recommend a great Indonesia travel spot to fellow travelers. Your submission will appear after admin review.",
    "app.placeLabel": "Place Name",
    "app.placePh": "e.g. Tegallalang Rice Terrace",
    "app.categoryLabel": "Category",
    "app.descLabel": "Your Review",
    "app.descPh": "Share your experience...",
    "app.addressLabel": "Address",
    "app.addressPh": "Search address...",
    "app.searchBtn": "Search",
    "app.instagramLabel": "Instagram Tags",
    "app.instagramPh": "@username or #hashtag",
    "app.authorLabel": "Your Name",
    "app.authorPh": "Your name",
    "app.cancelBtn": "Cancel",
    "app.submitBtn": "Submit",
    "app.submitted": "Thank you! Your spot will appear after admin review.",
    "app.submitError": "Failed to submit. Please try again.",
    "app.mapError": "Map could not be loaded.",

    "auth.signIn": "Sign In",
    "auth.signOut": "Sign Out",
    "auth.signInWith": "Sign in with Google",
    "auth.welcome": "Welcome",

    "bookmark.wantToVisit": "Want to Visit",
    "bookmark.interested": "Interested",
    "bookmark.remove": "Remove",
    "bookmark.saved": "Saved!",
    "bookmark.removed": "Removed",
    "bookmark.loginRequired": "Sign in to save spots",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "No saved spots yet",
    "bookmark.wantToVisitEmpty": "No 'Want to Visit' spots yet",
    "bookmark.interestedEmpty": "No 'Interested' spots yet",

    "planner.title": "AI Travel Planner",
    "planner.desc": "Plan your Indonesia trip based on your saved spots",
    "planner.days": "Trip Duration",
    "planner.daysUnit": "days",
    "planner.budget": "Budget",
    "planner.budgetBudget": "Budget-friendly",
    "planner.budgetModerate": "Moderate",
    "planner.budgetLuxury": "Luxury",
    "planner.style": "Travel Style",
    "planner.styleRelaxed": "Relaxed",
    "planner.styleBalanced": "Balanced",
    "planner.stylePacked": "Packed",
    "planner.spots": "Spots to Include",
    "planner.generate": "Generate Plan",
    "planner.generating": "Creating your travel plan...",
    "planner.result": "Your Travel Plan",
    "planner.retry": "Generate Again",
    "planner.close": "Close",
    "planner.noSpots": "Save spots as 'Want to Visit' first",
    "planner.error": "Failed to generate plan. Please try again.",
    "planner.rateLimit": "Daily limit reached ({limit} plans/day). Try again tomorrow!",
    "planner.remaining": "{n} plans remaining today",
    "planner.btn": "Create AI Travel Plan",
    "planner.btnFromSpot": "Plan with This Spot",
    "planner.targetNote": "AI builds itineraries from your \"Want to Visit\" list only.",
    "planner.save": "Save Plan",
    "planner.saved": "Plan saved!",
    "planner.myPlans": "My Plans",
    "planner.compare": "Compare",
    "planner.comparePlans": "Compare Plans",
    "planner.noSavedPlans": "No saved plans yet",
    "planner.deletePlan": "Delete",
    "planner.viewPlan": "View",
    "planner.planTitle": "{days}-Day Trip",
    "planner.spots_count": "{n} spots",
    "planner.savedLocal": "Saved on this device",
    "planner.selectToCompare": "Select 2-3 plans to compare",
    "planner.back": "Back",
    "planner.namePrompt": "Name this plan:",
    "planner.share": "Share",
    "planner.shareTitle": "Share this plan",
    "planner.copyLink": "Copy Link",
    "planner.sharing": "Creating share link...",

    "tips.btn": "Indonesia Travel Tips",
    "tips.title": "Indonesia Travel Tips",
    "tips.officialInfo": "Practical guidance for international visitors to Indonesia.",
    "tips.visa": "Visa & Entry",
    "tips.visaDesc": "Most nationalities need an e-VOA (Visa on Arrival, IDR 500,000 / ~USD 35) for stays up to 30 days, extendable once. ASEAN passport holders are visa-free. Pre-apply online at molina.imigrasi.go.id to skip the airport queue.",
    "tips.transport": "Getting Around",
    "tips.transportInterIsland": "Inter-island travel: domestic flights (Garuda, Citilink, Lion Air, Batik) for long distances; Pelni ferries for budget; speedboat between Bali ↔ Gili / Lombok / Nusa Penida.",
    "tips.transportLocal": "In cities: Gojek and Grab for ride-hailing (cheap and reliable). Avoid metered taxis except Bluebird (trusted brand).",
    "tips.transportBali": "In Bali: scooter rental (~IDR 80k/day) is the cheapest way to explore — bring an International Driving Permit.",
    "tips.currency": "Currency & Payment",
    "tips.currencyDesc": "Indonesian Rupiah (IDR). 1 USD ≈ IDR 16,000. Cards accepted in malls, hotels, and Bali tourist spots; cash needed elsewhere. ATMs at Indomaret / Alfamart / banks.",
    "tips.meals": "Meal Prices (Approximate)",
    "tips.budget": "Budget (~IDR 30,000)",
    "tips.budgetDesc": "Warung (local eateries), nasi goreng, mie goreng, padang food",
    "tips.moderate": "Moderate (IDR 50,000–150,000)",
    "tips.moderateDesc": "Mid-range restaurants, beach cafes, sushi, Western food",
    "tips.luxury": "Luxury (IDR 200,000+)",
    "tips.luxuryDesc": "Fine dining, beach clubs, Michelin-style restaurants in Bali / Jakarta",
    "tips.muslim": "For Muslim Travelers",
    "tips.muslimDesc": "Indonesia is the world's largest Muslim-majority country. Halal food is widely available. Prayer rooms (musholla) are in malls, gas stations, airports, and most public buildings. Friday prayer (12:00) may slow down service in non-tourist areas.",
    "tips.weather": "Weather",
    "tips.weatherDesc": "Tropical year-round (26–32°C). Dry season May–September (best for beach / hiking). Wet season October–April brings short heavy showers, usually in afternoon. Sunrise hikes (Bromo, Rinjani) need warm layers — temperatures drop to 5°C at altitude.",
    "tips.useful": "Useful Tips",
    "tips.bargain": "Bargaining is expected at traditional markets — start at 30–50% of the asking price.",
    "tips.water": "Drink only bottled or filtered water. Avoid ice in non-tourist areas.",
    "tips.modesty": "Cover shoulders and knees when visiting temples and mosques. Sarongs are usually provided at temple entrances.",
    "tips.tipping": "Tipping is not customary — service charge (5–10%) is often already included.",
    "tips.simcard": "Buy a Telkomsel or XL SIM at the airport (IDR 100,000 for 20GB / 30 days). Bring passport for registration.",
    "tips.emergency": "Emergency: 112 (general), 110 (police), 118 (ambulance), 119 (fire).",
    "tips.tourist": "Tourist Police: dial 110 then ask for English-speaking officer. In Bali: +62-361-754-599.",
    "tips.lastUpdated": "Information current as of 2026 · Sources: Indonesian Ministry of Tourism, official airline sites",

    "footer.text": "© 2026 Travel-ID. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
  },

  id: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — Jelajahi Indonesia | Panduan Wisata Lengkap",
    "seo.description": "Temukan tempat wisata terbaik di Indonesia yang direkomendasikan komunitas. Bali, Yogyakarta, Komodo, Bromo, Raja Ampat dan lainnya — dengan info halal, mushola, dan perencana perjalanan AI.",
    "seo.keywords": "wisata Indonesia, panduan wisata Bali, tour Yogyakarta, Borobudur, Komodo, Gunung Bromo, Raja Ampat, Lombok, perencana perjalanan, kuliner halal Bali, wisata muslim, tempat wisata Indonesia, peta wisata Indonesia",

    "nav.home": "Beranda",
    "nav.explore": "Jelajahi",
    "nav.lang": "English",

    "app.title": "Jelajahi Indonesia",
    "app.subtitle": "Tempat wisata yang direkomendasikan komunitas",
    "app.searchPh": "Cari tempat...",
    "app.catAll": "Semua",
    "app.catBeach": "Pantai",
    "app.catTemple": "Candi/Pura",
    "app.catCultural": "Budaya",
    "app.catVolcano": "Gunung Berapi",
    "app.catNature": "Alam",
    "app.catDiving": "Diving",
    "app.catFood": "Kuliner",
    "app.catCafe": "Kafe",
    "app.catShopping": "Belanja",
    "app.catNightlife": "Hiburan Malam",
    "app.catMuseum": "Museum",
    "app.catAdventure": "Petualangan",
    "app.catWellness": "Wellness",
    "app.catHalal": "Kuliner Halal",
    "app.catMosque": "Masjid / Mushola",
    "app.catVegetarian": "Vegetarian",
    "app.muslimToggle": "Ramah Muslim",
    "app.muslimDesc": "+ Restoran halal & mushola disertakan",

    "prefs.title": "Pengaturan Perjalanan",
    "prefs.dietary": "Preferensi",
    "prefs.muslim": "Ramah Muslim",
    "prefs.vegan": "Vegan",
    "prefs.visitType": "Jenis Kunjungan",
    "prefs.local": "Warga Lokal",
    "prefs.firstVisit": "Kunjungan Pertama (internasional)",
    "prefs.returnVisit": "Kunjungan Ulang (internasional)",
    "prefs.business": "Perjalanan Bisnis",
    "prefs.group": "Wisata Grup",
    "prefs.apply": "Terapkan",

    "guide.btn": "Cara Pakai",
    "guide.title": "Cara Menggunakan Travel-ID",
    "guide.step1Title": "Jelajah Tempat",
    "guide.step1Desc": "Telusuri tempat wisata di seluruh Indonesia yang direkomendasikan traveler. Filter berdasarkan kategori (Pantai, Candi, Gunung Berapi, dll.) dan wilayah (Bali, Yogyakarta, Komodo, …).",
    "guide.step2Title": "Pengaturan Perjalanan",
    "guide.step2Desc": "Tap ikon roda gigi untuk mengatur preferensi diet (Ramah Muslim, Vegan) dan jenis kunjungan. Ini memengaruhi rekomendasi peta dan AI planner.",
    "guide.step3Title": "Lihat Detail",
    "guide.step3Desc": "Tap tempat untuk melihat foto, deskripsi, alamat, info halal/mushola, dan harga tiket. Buka petunjuk arah di Google Maps dengan satu tap.",
    "guide.step4Title": "Peta & Daftar",
    "guide.step4Desc": "Di mobile, gunakan tombol Peta/Daftar di bawah. Di desktop, keduanya tampil bersebelahan.",
    "guide.step5Title": "Simpan & Bookmark",
    "guide.step5Desc": "Masuk dengan Google untuk menyimpan tempat sebagai 'Ingin Dikunjungi' atau 'Tertarik'. Tempat tersimpan muncul di tab My Spots dan menjadi input AI planner.",
    "guide.step6Title": "AI Trip Planner",
    "guide.step6Desc": "Setelah menyimpan tempat, buka Plan Trip dari menu. Pilih durasi, budget, dan gaya — AI menyusun itinerary harian termasuk transportasi antar-pulau (feri/penerbangan domestik) dan saran makanan.",
    "guide.dontShowAgain": "Jangan tampilkan lagi",
    "guide.dontShowToday": "Jangan tampilkan hari ini",

    "about.btn": "Tentang",
    "about.title": "Tentang Travel-ID",
    "about.privacy": "Kebijakan Privasi",
    "about.terms": "Syarat Layanan",
    "about.koinfo": "",

    "app.viewMap": "Peta",
    "app.viewList": "Daftar",
    "app.regionAll": "Semua Wilayah",
    "app.regionBali": "Bali",
    "app.regionJakarta": "Jakarta",
    "app.regionYogyakarta": "Yogyakarta",
    "app.regionBandung": "Bandung",
    "app.regionLombok": "Lombok",
    "app.regionKomodo": "Komodo",
    "app.regionSurabaya": "Surabaya",
    "app.regionMedan": "Medan",
    "app.regionBromo": "Bromo",
    "app.regionBorobudur": "Borobudur",
    "app.regionRajaAmpat": "Raja Ampat",
    "app.regionSumatra": "Sumatera",
    "app.regionSulawesi": "Sulawesi",
    "app.regionKalimantan": "Kalimantan",
    "app.regionOther": "Lainnya",

    "app.featured": "Pilihan",
    "app.rating": "Rating",
    "app.views": "Dilihat",
    "app.noResults": "Tidak ada hasil. Coba filter lain.",
    "app.loading": "Memuat...",
    "app.loadMore": "Muat Lebih Banyak",
    "app.openGoogle": "Buka di Google Maps",
    "app.mapGoogle": "Google Maps",
    "app.website": "Situs Resmi",
    "app.openingHours": "Jam Buka",
    "app.entryFee": "Harga Tiket",
    "app.entryFeeFree": "Gratis",
    "app.bestTime": "Waktu Terbaik",
    "app.localTips": "Tips Lokal",
    "app.halalBadge": "Halal",
    "app.prayerRoomBadge": "Mushola",
    "app.checkBusy": "Cek waktu ramai di Google Maps",
    "app.shareSpot": "Bagikan Tempat",
    "app.submitTitle": "Bagikan Tempat Wisata",
    "app.submitNotice": "Rekomendasikan tempat wisata Indonesia kepada traveler lain. Akan tampil setelah review admin.",
    "app.placeLabel": "Nama Tempat",
    "app.placePh": "contoh: Sawah Tegallalang",
    "app.categoryLabel": "Kategori",
    "app.descLabel": "Ulasan Anda",
    "app.descPh": "Bagikan pengalaman Anda...",
    "app.addressLabel": "Alamat",
    "app.addressPh": "Cari alamat...",
    "app.searchBtn": "Cari",
    "app.instagramLabel": "Tag Instagram",
    "app.instagramPh": "@username atau #hashtag",
    "app.authorLabel": "Nama Anda",
    "app.authorPh": "Nama",
    "app.cancelBtn": "Batal",
    "app.submitBtn": "Kirim",
    "app.submitted": "Terima kasih! Akan tampil setelah review admin.",
    "app.submitError": "Gagal mengirim. Coba lagi.",
    "app.mapError": "Peta tidak dapat dimuat.",

    "auth.signIn": "Masuk",
    "auth.signOut": "Keluar",
    "auth.signInWith": "Masuk dengan Google",
    "auth.welcome": "Selamat datang",

    "bookmark.wantToVisit": "Ingin Dikunjungi",
    "bookmark.interested": "Tertarik",
    "bookmark.remove": "Hapus",
    "bookmark.saved": "Tersimpan!",
    "bookmark.removed": "Dihapus",
    "bookmark.loginRequired": "Masuk untuk menyimpan tempat",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "Belum ada tempat tersimpan",
    "bookmark.wantToVisitEmpty": "Belum ada 'Ingin Dikunjungi'",
    "bookmark.interestedEmpty": "Belum ada 'Tertarik'",

    "planner.title": "AI Travel Planner",
    "planner.desc": "Rencanakan perjalanan Anda berdasarkan tempat tersimpan",
    "planner.days": "Durasi Perjalanan",
    "planner.daysUnit": "hari",
    "planner.budget": "Budget",
    "planner.budgetBudget": "Hemat",
    "planner.budgetModerate": "Sedang",
    "planner.budgetLuxury": "Mewah",
    "planner.style": "Gaya Perjalanan",
    "planner.styleRelaxed": "Santai",
    "planner.styleBalanced": "Seimbang",
    "planner.stylePacked": "Padat",
    "planner.spots": "Tempat",
    "planner.generate": "Buat Rencana",
    "planner.generating": "Membuat rencana perjalanan...",
    "planner.result": "Rencana Perjalanan Anda",
    "planner.retry": "Buat Ulang",
    "planner.close": "Tutup",
    "planner.noSpots": "Simpan tempat sebagai 'Ingin Dikunjungi' dulu",
    "planner.error": "Gagal membuat rencana. Coba lagi.",
    "planner.rateLimit": "Batas harian tercapai ({limit} rencana/hari). Coba besok!",
    "planner.remaining": "Sisa {n} rencana hari ini",
    "planner.btn": "Buat Rencana AI",
    "planner.btnFromSpot": "Rencanakan dengan Tempat Ini",
    "planner.targetNote": "AI hanya membuat rencana dari daftar \"Ingin Dikunjungi\" Anda.",
    "planner.save": "Simpan Rencana",
    "planner.saved": "Rencana tersimpan!",
    "planner.myPlans": "Rencana Saya",
    "planner.compare": "Bandingkan",
    "planner.comparePlans": "Bandingkan Rencana",
    "planner.noSavedPlans": "Belum ada rencana tersimpan",
    "planner.deletePlan": "Hapus",
    "planner.viewPlan": "Lihat",
    "planner.planTitle": "Trip {days} Hari",
    "planner.spots_count": "{n} tempat",
    "planner.savedLocal": "Tersimpan di perangkat ini",
    "planner.selectToCompare": "Pilih 2-3 rencana untuk dibandingkan",
    "planner.back": "Kembali",
    "planner.namePrompt": "Beri nama rencana:",
    "planner.share": "Bagikan",
    "planner.shareTitle": "Bagikan rencana ini",
    "planner.copyLink": "Salin Link",
    "planner.sharing": "Membuat link...",

    "tips.btn": "Tips Wisata Indonesia",
    "tips.title": "Tips Wisata Indonesia",
    "tips.officialInfo": "Panduan praktis untuk wisatawan asing di Indonesia.",
    "tips.visa": "Visa & Imigrasi",
    "tips.visaDesc": "Sebagian besar negara membutuhkan e-VOA (IDR 500.000 / ~35 USD) untuk kunjungan hingga 30 hari, dapat diperpanjang sekali. Pemegang paspor ASEAN bebas visa. Daftar online di molina.imigrasi.go.id untuk menghindari antrian bandara.",
    "tips.transport": "Transportasi",
    "tips.transportInterIsland": "Antar pulau: penerbangan domestik (Garuda, Citilink, Lion Air, Batik) untuk jarak jauh; feri Pelni untuk budget; speedboat antara Bali ↔ Gili/Lombok/Nusa Penida.",
    "tips.transportLocal": "Di kota: Gojek dan Grab untuk ride-hailing (murah dan andal). Hindari taksi argo kecuali Bluebird.",
    "tips.transportBali": "Di Bali: sewa motor (~Rp 80rb/hari) cara termurah menjelajah — bawa SIM Internasional.",
    "tips.currency": "Mata Uang & Pembayaran",
    "tips.currencyDesc": "Rupiah Indonesia (IDR). 1 USD ≈ Rp 16.000. Kartu diterima di mall, hotel, area wisata Bali; tunai diperlukan di tempat lain. ATM ada di Indomaret/Alfamart/bank.",
    "tips.meals": "Harga Makanan (Perkiraan)",
    "tips.budget": "Hemat (~Rp 30.000)",
    "tips.budgetDesc": "Warung, nasi goreng, mie goreng, masakan padang",
    "tips.moderate": "Sedang (Rp 50.000–150.000)",
    "tips.moderateDesc": "Restoran menengah, kafe pantai, sushi, masakan Barat",
    "tips.luxury": "Mewah (Rp 200.000+)",
    "tips.luxuryDesc": "Fine dining, beach club, restoran kelas Michelin di Bali/Jakarta",
    "tips.muslim": "Untuk Wisatawan Muslim",
    "tips.muslimDesc": "Indonesia adalah negara dengan populasi Muslim terbesar di dunia. Makanan halal mudah ditemukan. Mushola tersedia di mall, SPBU, bandara, dan gedung publik. Salat Jumat (12:00) bisa memperlambat layanan di area non-wisata.",
    "tips.weather": "Cuaca",
    "tips.weatherDesc": "Tropis sepanjang tahun (26–32°C). Musim kemarau Mei–September (terbaik untuk pantai/pendakian). Musim hujan Oktober–April membawa hujan lebat singkat, biasanya sore. Pendakian sunrise (Bromo, Rinjani) butuh pakaian hangat — suhu turun hingga 5°C di ketinggian.",
    "tips.useful": "Tips Berguna",
    "tips.bargain": "Tawar-menawar lazim di pasar tradisional — mulai dari 30–50% harga awal.",
    "tips.water": "Minum hanya air kemasan atau yang difilter. Hindari es di area non-wisata.",
    "tips.modesty": "Tutupi bahu dan lutut saat masuk pura/masjid. Sarung biasanya disediakan di pintu masuk pura.",
    "tips.tipping": "Tip tidak wajib — biaya layanan (5–10%) biasanya sudah termasuk.",
    "tips.simcard": "Beli SIM Telkomsel/XL di bandara (Rp 100.000 untuk 20GB/30 hari). Bawa paspor untuk registrasi.",
    "tips.emergency": "Darurat: 112 (umum), 110 (polisi), 118 (ambulans), 119 (kebakaran).",
    "tips.tourist": "Polisi Wisata: hubungi 110, minta petugas yang bisa berbahasa Inggris. Di Bali: +62-361-754-599.",
    "tips.lastUpdated": "Informasi per 2026 · Sumber: Kementerian Pariwisata RI, situs maskapai resmi",

    "footer.text": "© 2026 Travel-ID. Hak cipta dilindungi.",
    "footer.privacy": "Kebijakan Privasi",
    "footer.terms": "Syarat Layanan",
  },

  ko: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — 인도네시아 여행 가이드 | 발리부터 라자암팟까지",
    "seo.description": "커뮤니티가 추천하는 인도네시아 최고의 여행지를 발견하세요. 발리, 족자카르타, 코모도, 브로모, 라자암팟 — 할랄 식당과 기도실 정보, AI 여행 플래너 포함.",
    "seo.keywords": "인도네시아 여행, 발리 여행, 발리 가이드, 족자카르타, 보로부두르, 코모도, 브로모, 라자암팟, 롬복, 인도네시아 여행 일정, 인도네시아 맛집, 발리 할랄, 무슬림 친화 인도네시아, 인도네시아 명소, 인도네시아 지도",

    "nav.home": "홈",
    "nav.explore": "탐색",
    "nav.lang": "Bahasa",

    "app.title": "인도네시아를 발견하세요",
    "app.subtitle": "커뮤니티가 추천하는 여행지",
    "app.searchPh": "장소 검색...",
    "app.catAll": "전체",
    "app.catBeach": "해변",
    "app.catTemple": "사원/푸라",
    "app.catCultural": "문화",
    "app.catVolcano": "화산",
    "app.catNature": "자연",
    "app.catDiving": "다이빙",
    "app.catFood": "맛집",
    "app.catCafe": "카페",
    "app.catShopping": "쇼핑",
    "app.catNightlife": "나이트라이프",
    "app.catMuseum": "박물관",
    "app.catAdventure": "액티비티",
    "app.catWellness": "웰니스",
    "app.catHalal": "할랄 음식",
    "app.catMosque": "모스크/기도실",
    "app.catVegetarian": "채식",
    "app.muslimToggle": "무슬림 친화",
    "app.muslimDesc": "+ 할랄 식당 & 기도실(무솔라) 포함",

    "prefs.title": "여행 설정",
    "prefs.dietary": "선호도",
    "prefs.muslim": "무슬림 친화",
    "prefs.vegan": "비건",
    "prefs.visitType": "방문 유형",
    "prefs.local": "현지 거주자",
    "prefs.firstVisit": "첫 방문 (외국인)",
    "prefs.returnVisit": "재방문 (외국인)",
    "prefs.business": "출장",
    "prefs.group": "그룹 여행",
    "prefs.apply": "적용",

    "guide.btn": "사용법",
    "guide.title": "Travel-ID 사용법",
    "guide.step1Title": "장소 둘러보기",
    "guide.step1Desc": "인도네시아 전역의 추천 여행지를 탐색하세요. 카테고리(해변, 사원, 화산 등)와 지역(발리, 족자카르타, 코모도 등)으로 필터링할 수 있습니다.",
    "guide.step2Title": "여행 설정",
    "guide.step2Desc": "톱니바퀴 아이콘으로 식이 선호(무슬림 친화, 비건)와 방문 유형을 설정하세요. 지도 표시와 AI 플래너 추천에 반영됩니다.",
    "guide.step3Title": "장소 상세",
    "guide.step3Desc": "장소를 탭하면 사진, 설명, 주소, 할랄/기도실 표시, 입장료를 확인할 수 있습니다. 구글 지도에서 길찾기를 한 번에 열 수 있습니다.",
    "guide.step4Title": "지도 & 목록",
    "guide.step4Desc": "모바일에서는 하단의 지도/목록 버튼으로 전환하세요. 데스크톱에서는 두 가지가 나란히 표시됩니다.",
    "guide.step5Title": "저장 & 북마크",
    "guide.step5Desc": "Google로 로그인하면 장소를 '방문할 곳' 또는 '관심 있음'으로 저장할 수 있습니다. 저장된 장소는 My Spots 탭에 나타나고 AI 플래너의 입력이 됩니다.",
    "guide.step6Title": "AI 여행 플래너",
    "guide.step6Desc": "장소를 저장한 후 메뉴에서 'Plan Trip'을 여세요. 기간, 예산, 스타일을 선택하면 AI가 섬간 이동(페리/국내선)과 식사 추천을 포함한 일자별 일정을 만들어 줍니다.",
    "guide.dontShowAgain": "다시 보지 않기",
    "guide.dontShowToday": "오늘 다시 안보기",

    "about.btn": "앱 정보",
    "about.title": "Travel-ID 정보",
    "about.privacy": "개인정보처리방침",
    "about.terms": "이용약관",
    "about.koinfo": "",

    "app.viewMap": "지도",
    "app.viewList": "목록",
    "app.regionAll": "전체 지역",
    "app.regionBali": "발리",
    "app.regionJakarta": "자카르타",
    "app.regionYogyakarta": "족자카르타",
    "app.regionBandung": "반둥",
    "app.regionLombok": "롬복",
    "app.regionKomodo": "코모도",
    "app.regionSurabaya": "수라바야",
    "app.regionMedan": "메단",
    "app.regionBromo": "브로모",
    "app.regionBorobudur": "보로부두르",
    "app.regionRajaAmpat": "라자암팟",
    "app.regionSumatra": "수마트라",
    "app.regionSulawesi": "술라웨시",
    "app.regionKalimantan": "칼리만탄",
    "app.regionOther": "기타",

    "app.featured": "추천",
    "app.rating": "평점",
    "app.views": "조회",
    "app.noResults": "검색 결과가 없습니다. 다른 필터를 시도해 보세요.",
    "app.loading": "불러오는 중...",
    "app.loadMore": "더 보기",
    "app.openGoogle": "구글 지도에서 열기",
    "app.mapGoogle": "구글 지도",
    "app.website": "공식 홈페이지",
    "app.openingHours": "영업시간",
    "app.entryFee": "입장료",
    "app.entryFeeFree": "무료",
    "app.bestTime": "방문 추천 시기",
    "app.localTips": "현지 팁",
    "app.halalBadge": "할랄",
    "app.prayerRoomBadge": "기도실",
    "app.checkBusy": "구글 지도에서 혼잡도 확인",
    "app.shareSpot": "내 장소 등록",
    "app.submitTitle": "인도네시아 여행지 등록",
    "app.submitNotice": "내가 알고 있는 인도네시아 여행지를 다른 여행자에게 공유해주세요. 등록 후 관리자 승인을 거쳐 게시됩니다.",
    "app.placeLabel": "장소 이름",
    "app.placePh": "예: 떼갈랄랑 라이스 테라스",
    "app.categoryLabel": "카테고리",
    "app.descLabel": "리뷰",
    "app.descPh": "경험을 공유하세요...",
    "app.addressLabel": "주소",
    "app.addressPh": "주소 검색...",
    "app.searchBtn": "검색",
    "app.instagramLabel": "인스타그램 태그",
    "app.instagramPh": "@계정 또는 #해시태그",
    "app.authorLabel": "작성자",
    "app.authorPh": "이름",
    "app.cancelBtn": "취소",
    "app.submitBtn": "제출",
    "app.submitted": "감사합니다! 관리자 승인 후 게시됩니다.",
    "app.submitError": "제출에 실패했습니다. 다시 시도해 주세요.",
    "app.mapError": "지도를 불러올 수 없습니다.",

    "auth.signIn": "로그인",
    "auth.signOut": "로그아웃",
    "auth.signInWith": "Google로 로그인",
    "auth.welcome": "환영합니다",

    "bookmark.wantToVisit": "방문할 곳",
    "bookmark.interested": "관심 있음",
    "bookmark.remove": "삭제",
    "bookmark.saved": "저장됨!",
    "bookmark.removed": "삭제됨",
    "bookmark.loginRequired": "로그인 후 저장 가능",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "저장된 장소가 없습니다",
    "bookmark.wantToVisitEmpty": "'방문할 곳'에 저장된 장소가 없습니다",
    "bookmark.interestedEmpty": "'관심 있음'에 저장된 장소가 없습니다",

    "planner.title": "AI 여행 플래너",
    "planner.desc": "저장한 장소 기반으로 인도네시아 여행 일정을 만들어 드립니다",
    "planner.days": "여행 기간",
    "planner.daysUnit": "일",
    "planner.budget": "예산",
    "planner.budgetBudget": "알뜰",
    "planner.budgetModerate": "보통",
    "planner.budgetLuxury": "럭셔리",
    "planner.style": "여행 스타일",
    "planner.styleRelaxed": "여유롭게",
    "planner.styleBalanced": "균형",
    "planner.stylePacked": "꽉 채워서",
    "planner.spots": "포함할 장소",
    "planner.generate": "일정 만들기",
    "planner.generating": "여행 일정 생성 중...",
    "planner.result": "여행 일정",
    "planner.retry": "다시 만들기",
    "planner.close": "닫기",
    "planner.noSpots": "먼저 '방문할 곳'에 장소를 저장하세요",
    "planner.error": "일정 생성에 실패했습니다. 다시 시도해 주세요.",
    "planner.rateLimit": "오늘 생성 한도({limit}회)에 도달했습니다. 내일 다시 시도해 주세요!",
    "planner.remaining": "오늘 {n}회 남았습니다",
    "planner.btn": "AI 여행 일정 만들기",
    "planner.btnFromSpot": "이 장소로 일정 짜기",
    "planner.targetNote": "AI는 \"방문할 곳\" 목록만으로 일정을 만듭니다.",
    "planner.save": "일정 저장",
    "planner.saved": "일정이 저장되었습니다!",
    "planner.myPlans": "내 일정",
    "planner.compare": "비교",
    "planner.comparePlans": "일정 비교",
    "planner.noSavedPlans": "저장된 일정이 없습니다",
    "planner.deletePlan": "삭제",
    "planner.viewPlan": "보기",
    "planner.planTitle": "{days}일 일정",
    "planner.spots_count": "{n}곳",
    "planner.savedLocal": "이 기기에 저장됨",
    "planner.selectToCompare": "2-3개 일정을 선택하여 비교",
    "planner.back": "뒤로",
    "planner.namePrompt": "일정 이름:",
    "planner.share": "공유",
    "planner.shareTitle": "이 일정 공유하기",
    "planner.copyLink": "링크 복사",
    "planner.sharing": "공유 링크 생성 중...",

    "tips.btn": "인도네시아 여행 팁",
    "tips.title": "인도네시아 여행 팁",
    "tips.officialInfo": "한국인 여행자를 위한 실용적인 인도네시아 여행 정보.",
    "tips.visa": "비자 & 입국",
    "tips.visaDesc": "한국 여권 소지자는 도착비자(e-VOA, IDR 500,000/약 4.5만원)로 30일까지 체류 가능, 1회 연장 가능. molina.imigrasi.go.id에서 사전 신청 시 공항 대기열 회피.",
    "tips.transport": "교통수단",
    "tips.transportInterIsland": "섬간 이동: 장거리는 국내선(Garuda, Citilink, Lion Air, Batik), 저예산은 Pelni 페리, 발리↔길리/롬복/누사페니다는 스피드보트.",
    "tips.transportLocal": "도시 내: Gojek, Grab 라이드헤일링이 저렴하고 안전. 일반 미터 택시는 피하고 Bluebird만 추천.",
    "tips.transportBali": "발리: 스쿠터 렌트(약 8만 IDR/일)가 가장 저렴한 이동 수단. 국제운전면허증 필수.",
    "tips.currency": "통화 & 결제",
    "tips.currencyDesc": "인도네시아 루피아(IDR). 1 USD ≈ IDR 16,000, 100원 ≈ IDR 1,200. 카드는 쇼핑몰/호텔/발리 관광지에서 통용, 그 외엔 현금. Indomaret/Alfamart/은행 ATM 사용.",
    "tips.meals": "식사 가격(대략)",
    "tips.budget": "알뜰 (~IDR 30,000 / 약 3천원)",
    "tips.budgetDesc": "와룽(현지 식당), 나시고렝, 미고렝, 빠당 음식",
    "tips.moderate": "보통 (IDR 50,000~150,000 / 약 5천~1만5천원)",
    "tips.moderateDesc": "중급 식당, 비치 카페, 스시, 양식",
    "tips.luxury": "럭셔리 (IDR 200,000+ / 2만원+)",
    "tips.luxuryDesc": "파인다이닝, 비치클럽, 발리/자카르타 미슐랭급 레스토랑",
    "tips.muslim": "무슬림 여행자",
    "tips.muslimDesc": "인도네시아는 세계 최대 무슬림 인구 국가. 할랄 음식이 일반적. 쇼핑몰/주유소/공항/공공건물에 기도실(무솔라) 비치. 금요일 정오 예배 시간(12:00)에는 비관광지에서 영업이 잠시 멈출 수 있음.",
    "tips.weather": "날씨",
    "tips.weatherDesc": "연중 열대 기후(26~32°C). 건기 5~9월(해변/등산 최적). 우기 10~4월은 짧고 강한 소나기, 보통 오후. 일출 등반(브로모, 린자니)은 보온 필수 — 고지대는 5°C까지 내려감.",
    "tips.useful": "유용한 팁",
    "tips.bargain": "재래시장에선 흥정이 일반적 — 호가의 30~50%부터 시작.",
    "tips.water": "생수나 정수만 마시고, 비관광지에선 얼음 피하기.",
    "tips.modesty": "사원/모스크 방문 시 어깨와 무릎을 가리세요. 사원 입구에 사롱 대여 가능.",
    "tips.tipping": "팁 문화는 없음 — 서비스 차지(5~10%)가 청구서에 포함된 경우가 많음.",
    "tips.simcard": "공항에서 Telkomsel 또는 XL 심카드(IDR 100,000 / 20GB·30일). 등록 시 여권 필수.",
    "tips.emergency": "긴급: 112(공통), 110(경찰), 118(구급), 119(소방).",
    "tips.tourist": "관광경찰: 110에 영어 가능 직원 요청. 발리: +62-361-754-599.",
    "tips.korean": "주인도네시아 한국대사관: +62-21-2967-2555 (자카르타). 영사콜센터(24h): 외교부 +82-2-3210-0404.",
    "tips.lastUpdated": "정보 기준 2026년 · 출처: 인도네시아 관광부, 항공사 공식 사이트",

    "footer.text": "© 2026 Travel-ID. All rights reserved.",
    "footer.privacy": "개인정보처리방침",
    "footer.terms": "이용약관",
  },

  zh: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — 探索印度尼西亚 | 巴厘岛及更多旅游指南",
    "seo.description": "发现社区推荐的印尼最佳旅游胜地。巴厘岛、日惹、科莫多、布罗莫、四王群岛等 — 含清真餐厅、礼拜室及AI行程规划。",
    "seo.keywords": "印度尼西亚旅游, 巴厘岛旅游, 巴厘岛攻略, 日惹, 婆罗浮屠, 科莫多, 布罗莫火山, 四王群岛, 龙目岛, 印尼行程, 巴厘岛美食, 印尼穆斯林友好, 印尼景点, 印尼地图",

    "nav.home": "首页",
    "nav.explore": "探索",
    "nav.lang": "Bahasa",

    "app.title": "探索印度尼西亚",
    "app.subtitle": "社区推荐的旅游胜地",
    "app.searchPh": "搜索地点...",
    "app.catAll": "全部",
    "app.catBeach": "海滩",
    "app.catTemple": "寺庙/普拉",
    "app.catCultural": "文化",
    "app.catVolcano": "火山",
    "app.catNature": "自然",
    "app.catDiving": "潜水",
    "app.catFood": "美食",
    "app.catCafe": "咖啡馆",
    "app.catShopping": "购物",
    "app.catNightlife": "夜生活",
    "app.catMuseum": "博物馆",
    "app.catAdventure": "探险",
    "app.catWellness": "养生",
    "app.catHalal": "清真美食",
    "app.catMosque": "清真寺/礼拜室",
    "app.catVegetarian": "素食",
    "app.muslimToggle": "穆斯林友好",
    "app.muslimDesc": "+ 包含清真餐厅与礼拜室",

    "prefs.title": "旅行设置",
    "prefs.dietary": "饮食偏好",
    "prefs.muslim": "穆斯林友好",
    "prefs.vegan": "纯素",
    "prefs.visitType": "访问类型",
    "prefs.local": "本地居民",
    "prefs.firstVisit": "首次访问(国际)",
    "prefs.returnVisit": "再次访问(国际)",
    "prefs.business": "商务出行",
    "prefs.group": "团体旅行",
    "prefs.apply": "应用",

    "guide.btn": "使用说明",
    "guide.title": "Travel-ID 使用方法",
    "guide.step1Title": "浏览地点",
    "guide.step1Desc": "探索印尼各地由旅行者推荐的旅游胜地。可按分类(海滩、寺庙、火山等)和地区(巴厘岛、日惹、科莫多等)筛选。",
    "guide.step2Title": "旅行设置",
    "guide.step2Desc": "点击齿轮图标设置饮食偏好(穆斯林友好、纯素)和访问类型。这会影响地图显示和AI规划推荐。",
    "guide.step3Title": "查看详情",
    "guide.step3Desc": "点击任意地点查看照片、描述、地址、清真/礼拜室标记及门票费用。一键打开Google地图导航。",
    "guide.step4Title": "地图与列表",
    "guide.step4Desc": "在手机上,使用底部的地图/列表按钮切换。在桌面端,两种视图并排显示。",
    "guide.step5Title": "保存与收藏",
    "guide.step5Desc": "用Google登录可将地点保存为'想去'或'感兴趣'。已保存的地点显示在My Spots标签页,作为AI规划的输入。",
    "guide.step6Title": "AI行程规划",
    "guide.step6Desc": "保存地点后,从菜单打开规划行程。选择天数、预算和风格 — AI会生成包含跨岛交通(轮渡/国内航班)和餐饮推荐的逐日行程。",
    "guide.dontShowAgain": "不再显示",
    "guide.dontShowToday": "今日不再显示",

    "about.btn": "关于",
    "about.title": "关于 Travel-ID",
    "about.privacy": "隐私政策",
    "about.terms": "服务条款",
    "about.koinfo": "",

    "app.viewMap": "地图",
    "app.viewList": "列表",
    "app.regionAll": "所有地区",
    "app.regionBali": "巴厘岛",
    "app.regionJakarta": "雅加达",
    "app.regionYogyakarta": "日惹",
    "app.regionBandung": "万隆",
    "app.regionLombok": "龙目岛",
    "app.regionKomodo": "科莫多",
    "app.regionSurabaya": "泗水",
    "app.regionMedan": "棉兰",
    "app.regionBromo": "布罗莫",
    "app.regionBorobudur": "婆罗浮屠",
    "app.regionRajaAmpat": "四王群岛",
    "app.regionSumatra": "苏门答腊",
    "app.regionSulawesi": "苏拉威西",
    "app.regionKalimantan": "加里曼丹",
    "app.regionOther": "其他",

    "app.featured": "推荐",
    "app.rating": "评分",
    "app.views": "浏览",
    "app.noResults": "未找到结果。请尝试其他筛选。",
    "app.loading": "加载中...",
    "app.loadMore": "加载更多",
    "app.openGoogle": "在 Google 地图打开",
    "app.mapGoogle": "Google 地图",
    "app.website": "官方网站",
    "app.openingHours": "营业时间",
    "app.entryFee": "门票",
    "app.entryFeeFree": "免费",
    "app.bestTime": "最佳访问时间",
    "app.localTips": "当地贴士",
    "app.halalBadge": "清真",
    "app.prayerRoomBadge": "礼拜室",
    "app.checkBusy": "在 Google 地图查看忙碌时段",
    "app.shareSpot": "分享地点",
    "app.submitTitle": "分享印尼旅游地点",
    "app.submitNotice": "向其他旅行者推荐你了解的印尼旅游地点。审核通过后将显示。",
    "app.placeLabel": "地点名称",
    "app.placePh": "如:德格拉朗梯田",
    "app.categoryLabel": "分类",
    "app.descLabel": "你的评价",
    "app.descPh": "分享你的体验...",
    "app.addressLabel": "地址",
    "app.addressPh": "搜索地址...",
    "app.searchBtn": "搜索",
    "app.instagramLabel": "Instagram 标签",
    "app.instagramPh": "@用户名 或 #话题",
    "app.authorLabel": "你的姓名",
    "app.authorPh": "姓名",
    "app.cancelBtn": "取消",
    "app.submitBtn": "提交",
    "app.submitted": "感谢!审核通过后将显示。",
    "app.submitError": "提交失败,请重试。",
    "app.mapError": "无法加载地图。",

    "auth.signIn": "登录",
    "auth.signOut": "登出",
    "auth.signInWith": "使用 Google 登录",
    "auth.welcome": "欢迎",

    "bookmark.wantToVisit": "想去",
    "bookmark.interested": "感兴趣",
    "bookmark.remove": "移除",
    "bookmark.saved": "已保存!",
    "bookmark.removed": "已移除",
    "bookmark.loginRequired": "请登录后保存",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "暂无收藏",
    "bookmark.wantToVisitEmpty": "暂无'想去'地点",
    "bookmark.interestedEmpty": "暂无'感兴趣'地点",

    "planner.title": "AI 行程规划",
    "planner.desc": "基于已保存地点规划印尼行程",
    "planner.days": "行程天数",
    "planner.daysUnit": "天",
    "planner.budget": "预算",
    "planner.budgetBudget": "经济",
    "planner.budgetModerate": "中等",
    "planner.budgetLuxury": "奢华",
    "planner.style": "旅行风格",
    "planner.styleRelaxed": "悠闲",
    "planner.styleBalanced": "平衡",
    "planner.stylePacked": "紧凑",
    "planner.spots": "包含地点",
    "planner.generate": "生成行程",
    "planner.generating": "正在生成行程...",
    "planner.result": "你的行程",
    "planner.retry": "重新生成",
    "planner.close": "关闭",
    "planner.noSpots": "请先将地点保存为'想去'",
    "planner.error": "生成失败,请重试。",
    "planner.rateLimit": "今日已达上限({limit}次/天),请明日再试!",
    "planner.remaining": "今日剩余 {n} 次",
    "planner.btn": "创建AI行程",
    "planner.btnFromSpot": "用此地点规划",
    "planner.targetNote": "AI 仅基于你的\"想去\"列表生成行程。",
    "planner.save": "保存行程",
    "planner.saved": "行程已保存!",
    "planner.myPlans": "我的行程",
    "planner.compare": "对比",
    "planner.comparePlans": "对比行程",
    "planner.noSavedPlans": "暂无保存行程",
    "planner.deletePlan": "删除",
    "planner.viewPlan": "查看",
    "planner.planTitle": "{days}天行程",
    "planner.spots_count": "{n}个地点",
    "planner.savedLocal": "已保存到本设备",
    "planner.selectToCompare": "选择 2-3 个行程进行对比",
    "planner.back": "返回",
    "planner.namePrompt": "为行程命名:",
    "planner.share": "分享",
    "planner.shareTitle": "分享此行程",
    "planner.copyLink": "复制链接",
    "planner.sharing": "正在创建分享链接...",

    "tips.btn": "印尼旅行贴士",
    "tips.title": "印尼旅行贴士",
    "tips.officialInfo": "面向中国游客的实用印尼旅行信息。",
    "tips.visa": "签证与入境",
    "tips.visaDesc": "中国护照持有者可办落地签 e-VOA(IDR 500,000 / 约 ¥230)停留30天,可延期一次。建议在 molina.imigrasi.go.id 提前在线申请,避开机场排队。",
    "tips.transport": "交通",
    "tips.transportInterIsland": "跨岛:长途用国内航班(Garuda, Citilink, Lion Air, Batik);经济选 Pelni 轮渡;巴厘岛↔吉利/龙目/努沙佩尼达走快艇。",
    "tips.transportLocal": "市内:Gojek 与 Grab 网约车便宜可靠。除 Bluebird 外避免使用打表出租车。",
    "tips.transportBali": "巴厘岛:租摩托车(约 IDR 80,000/天)是最经济的出行方式 — 需国际驾照。",
    "tips.currency": "货币与支付",
    "tips.currencyDesc": "印尼盾(IDR)。1 USD ≈ IDR 16,000,1 RMB ≈ IDR 2,200。商场、酒店、巴厘岛景区可刷卡;其他地方需现金。Indomaret/Alfamart/银行 ATM 都可取现。",
    "tips.meals": "餐饮价格(参考)",
    "tips.budget": "经济(~IDR 30,000 / ¥15)",
    "tips.budgetDesc": "Warung 路边店、炒饭、炒面、巴东菜",
    "tips.moderate": "中等(IDR 50,000–150,000 / ¥25–70)",
    "tips.moderateDesc": "中档餐厅、海边咖啡、寿司、西餐",
    "tips.luxury": "奢华(IDR 200,000+ / ¥100+)",
    "tips.luxuryDesc": "高级餐厅、海滩俱乐部、巴厘岛/雅加达米其林级餐厅",
    "tips.muslim": "穆斯林游客",
    "tips.muslimDesc": "印尼是世界穆斯林人口最多的国家。清真餐随处可见。商场、加油站、机场、公共建筑均设礼拜室(musholla)。周五正午礼拜(12:00)在非旅游区可能短暂歇业。",
    "tips.weather": "天气",
    "tips.weatherDesc": "全年热带气候(26–32°C)。旱季5–9月(海滩/登山最佳)。雨季10–4月多短时强降雨,常在午后。日出登山(布罗莫、林贾尼)需保暖 — 高海拔可降至5°C。",
    "tips.useful": "实用提醒",
    "tips.bargain": "传统市场可砍价 — 从开价的30–50%开始还。",
    "tips.water": "只喝瓶装水或过滤水。非旅游区避免食用冰块。",
    "tips.modesty": "进入寺庙/清真寺时需遮盖肩膀和膝盖。寺庙入口通常提供纱笼。",
    "tips.tipping": "无小费文化 — 服务费(5–10%)通常已包含在账单中。",
    "tips.simcard": "机场购买 Telkomsel 或 XL 电话卡(IDR 100,000 / 20GB·30天),需护照实名登记。",
    "tips.emergency": "紧急电话:112(综合)、110(警察)、118(救护)、119(消防)。",
    "tips.tourist": "旅游警察:拨110并要求英文服务。巴厘岛:+62-361-754-599。",
    "tips.korean": "驻印尼中国大使馆:+62-21-525-1981(雅加达)。",
    "tips.lastUpdated": "信息截至 2026 年 · 来源:印尼旅游部、各航空公司官方网站",

    "footer.text": "© 2026 Travel-ID. 版权所有。",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
  },

  ja: {
    "common.tagline": "Travel-ID",

    "seo.title": "Travel-ID — インドネシア旅行ガイド | バリ島から先へ",
    "seo.description": "コミュニティ推薦のインドネシア最高の観光地を発見。バリ島、ジョグジャカルタ、コモド、ブロモ、ラジャアンパット - ハラル料理・礼拝室情報、AI旅行プランナー付き。",
    "seo.keywords": "インドネシア旅行, バリ島旅行, バリ島ガイド, ジョグジャカルタ, ボロブドゥール, コモド, ブロモ山, ラジャアンパット, ロンボク, インドネシア観光, バリグルメ, ムスリムフレンドリー インドネシア, インドネシア観光地, インドネシア地図",

    "nav.home": "ホーム",
    "nav.explore": "探索",
    "nav.lang": "Bahasa",

    "app.title": "インドネシアを発見しよう",
    "app.subtitle": "コミュニティが推薦する観光地",
    "app.searchPh": "場所を検索...",
    "app.catAll": "すべて",
    "app.catBeach": "ビーチ",
    "app.catTemple": "寺院/プラ",
    "app.catCultural": "文化",
    "app.catVolcano": "火山",
    "app.catNature": "自然",
    "app.catDiving": "ダイビング",
    "app.catFood": "グルメ",
    "app.catCafe": "カフェ",
    "app.catShopping": "ショッピング",
    "app.catNightlife": "ナイトライフ",
    "app.catMuseum": "博物館",
    "app.catAdventure": "アドベンチャー",
    "app.catWellness": "ウェルネス",
    "app.catHalal": "ハラルフード",
    "app.catMosque": "モスク/礼拝室",
    "app.catVegetarian": "ベジタリアン",
    "app.muslimToggle": "ムスリムフレンドリー",
    "app.muslimDesc": "+ ハラルレストラン&礼拝室(ムショラ)を含む",

    "prefs.title": "旅行設定",
    "prefs.dietary": "好み",
    "prefs.muslim": "ムスリムフレンドリー",
    "prefs.vegan": "ヴィーガン",
    "prefs.visitType": "訪問タイプ",
    "prefs.local": "現地居住者",
    "prefs.firstVisit": "初訪問(海外から)",
    "prefs.returnVisit": "再訪問(海外から)",
    "prefs.business": "出張",
    "prefs.group": "団体旅行",
    "prefs.apply": "適用",

    "guide.btn": "使い方",
    "guide.title": "Travel-IDの使い方",
    "guide.step1Title": "観光地を見る",
    "guide.step1Desc": "インドネシア全土の旅行者推薦スポットを探索。カテゴリ(ビーチ、寺院、火山など)と地域(バリ、ジョグジャ、コモドなど)で絞り込めます。",
    "guide.step2Title": "旅行設定",
    "guide.step2Desc": "歯車アイコンで食の好み(ムスリムフレンドリー、ヴィーガン)と訪問タイプを設定。地図表示とAIプランナーの推薦に反映されます。",
    "guide.step3Title": "詳細表示",
    "guide.step3Desc": "スポットをタップで写真、説明、住所、ハラル/礼拝室マーク、入場料を確認。ワンタップでGoogleマップのルート案内を起動。",
    "guide.step4Title": "地図とリスト",
    "guide.step4Desc": "モバイルでは下部の地図/リストボタンで切替。デスクトップでは左右に並んで表示。",
    "guide.step5Title": "保存とブックマーク",
    "guide.step5Desc": "Googleでログインしてスポットを「行きたい」または「興味あり」に保存。My Spotsタブに表示され、AIプランナーの入力になります。",
    "guide.step6Title": "AI旅行プランナー",
    "guide.step6Desc": "スポット保存後、メニューからPlan Tripを開く。期間、予算、スタイルを選ぶと、AIが島間移動(フェリー/国内線)と食事提案を含む日別プランを作成。",
    "guide.dontShowAgain": "今後表示しない",
    "guide.dontShowToday": "今日は表示しない",

    "about.btn": "アプリについて",
    "about.title": "Travel-ID について",
    "about.privacy": "プライバシーポリシー",
    "about.terms": "利用規約",
    "about.koinfo": "",

    "app.viewMap": "地図",
    "app.viewList": "リスト",
    "app.regionAll": "全地域",
    "app.regionBali": "バリ島",
    "app.regionJakarta": "ジャカルタ",
    "app.regionYogyakarta": "ジョグジャカルタ",
    "app.regionBandung": "バンドン",
    "app.regionLombok": "ロンボク",
    "app.regionKomodo": "コモド",
    "app.regionSurabaya": "スラバヤ",
    "app.regionMedan": "メダン",
    "app.regionBromo": "ブロモ",
    "app.regionBorobudur": "ボロブドゥール",
    "app.regionRajaAmpat": "ラジャアンパット",
    "app.regionSumatra": "スマトラ",
    "app.regionSulawesi": "スラウェシ",
    "app.regionKalimantan": "カリマンタン",
    "app.regionOther": "その他",

    "app.featured": "おすすめ",
    "app.rating": "評価",
    "app.views": "閲覧",
    "app.noResults": "該当なし。別のフィルターをお試しください。",
    "app.loading": "読み込み中...",
    "app.loadMore": "さらに読み込む",
    "app.openGoogle": "Google マップで開く",
    "app.mapGoogle": "Google マップ",
    "app.website": "公式サイト",
    "app.openingHours": "営業時間",
    "app.entryFee": "入場料",
    "app.entryFeeFree": "無料",
    "app.bestTime": "ベストシーズン",
    "app.localTips": "現地情報",
    "app.halalBadge": "ハラル",
    "app.prayerRoomBadge": "礼拝室",
    "app.checkBusy": "Google マップで混雑状況を確認",
    "app.shareSpot": "スポットを投稿",
    "app.submitTitle": "インドネシアの観光地を投稿",
    "app.submitNotice": "あなたが知っているインドネシアの素敵なスポットを他の旅行者にシェア。管理者承認後に公開されます。",
    "app.placeLabel": "場所の名前",
    "app.placePh": "例: テガラランの棚田",
    "app.categoryLabel": "カテゴリ",
    "app.descLabel": "あなたのレビュー",
    "app.descPh": "体験を共有してください...",
    "app.addressLabel": "住所",
    "app.addressPh": "住所を検索...",
    "app.searchBtn": "検索",
    "app.instagramLabel": "Instagram タグ",
    "app.instagramPh": "@ユーザー名 または #ハッシュタグ",
    "app.authorLabel": "あなたの名前",
    "app.authorPh": "名前",
    "app.cancelBtn": "キャンセル",
    "app.submitBtn": "送信",
    "app.submitted": "ありがとうございます!管理者承認後に公開されます。",
    "app.submitError": "送信に失敗しました。再度お試しください。",
    "app.mapError": "地図を読み込めませんでした。",

    "auth.signIn": "ログイン",
    "auth.signOut": "ログアウト",
    "auth.signInWith": "Google でログイン",
    "auth.welcome": "ようこそ",

    "bookmark.wantToVisit": "行きたい",
    "bookmark.interested": "興味あり",
    "bookmark.remove": "削除",
    "bookmark.saved": "保存しました!",
    "bookmark.removed": "削除しました",
    "bookmark.loginRequired": "ログインして保存",
    "bookmark.mySpots": "My Spots",
    "bookmark.noBookmarks": "保存済みなし",
    "bookmark.wantToVisitEmpty": "「行きたい」スポットなし",
    "bookmark.interestedEmpty": "「興味あり」スポットなし",

    "planner.title": "AI旅行プランナー",
    "planner.desc": "保存したスポットを基にインドネシア旅行を計画",
    "planner.days": "旅行日数",
    "planner.daysUnit": "日",
    "planner.budget": "予算",
    "planner.budgetBudget": "節約",
    "planner.budgetModerate": "標準",
    "planner.budgetLuxury": "贅沢",
    "planner.style": "旅行スタイル",
    "planner.styleRelaxed": "ゆったり",
    "planner.styleBalanced": "バランス",
    "planner.stylePacked": "詰め込み",
    "planner.spots": "含めるスポット",
    "planner.generate": "プラン作成",
    "planner.generating": "プラン作成中...",
    "planner.result": "あなたの旅行プラン",
    "planner.retry": "再作成",
    "planner.close": "閉じる",
    "planner.noSpots": "まず「行きたい」にスポットを保存",
    "planner.error": "プラン作成に失敗。再度お試しください。",
    "planner.rateLimit": "今日の上限({limit}回)に達しました。明日また!",
    "planner.remaining": "本日残り {n} 回",
    "planner.btn": "AI旅行プラン作成",
    "planner.btnFromSpot": "このスポットでプラン",
    "planner.targetNote": "AIは「行きたい」リストのみからプランを作成します。",
    "planner.save": "プラン保存",
    "planner.saved": "プランを保存しました!",
    "planner.myPlans": "マイプラン",
    "planner.compare": "比較",
    "planner.comparePlans": "プラン比較",
    "planner.noSavedPlans": "保存済みプランなし",
    "planner.deletePlan": "削除",
    "planner.viewPlan": "表示",
    "planner.planTitle": "{days}日間プラン",
    "planner.spots_count": "{n}スポット",
    "planner.savedLocal": "この端末に保存",
    "planner.selectToCompare": "2-3 個のプランを選択して比較",
    "planner.back": "戻る",
    "planner.namePrompt": "プラン名:",
    "planner.share": "シェア",
    "planner.shareTitle": "このプランをシェア",
    "planner.copyLink": "リンクをコピー",
    "planner.sharing": "共有リンクを作成中...",

    "tips.btn": "インドネシア旅行のヒント",
    "tips.title": "インドネシア旅行のヒント",
    "tips.officialInfo": "日本人旅行者向けインドネシア旅行の実用情報。",
    "tips.visa": "ビザと入国",
    "tips.visaDesc": "日本旅券保持者は到着ビザ(e-VOA, IDR 500,000 / 約4,500円)で30日滞在可、1回延長可。molina.imigrasi.go.id でオンライン事前申請すると空港の列を回避できる。",
    "tips.transport": "交通",
    "tips.transportInterIsland": "島間移動:長距離は国内線(ガルーダ、シティリンク、ライオンエア、バティック)、節約はPelniフェリー、バリ↔ギリ/ロンボク/ヌサペニダはスピードボート。",
    "tips.transportLocal": "市内:Gojek と Grab の配車が安くて安心。メータータクシーはBluebird以外避ける。",
    "tips.transportBali": "バリ島:バイクレンタル(約 IDR 80,000/日)が最も経済的。国際運転免許証必須。",
    "tips.currency": "通貨と支払い",
    "tips.currencyDesc": "インドネシアルピア(IDR)。1 USD ≈ IDR 16,000、100円 ≈ IDR 1,100。モール・ホテル・バリ観光地はカード可、その他は現金。Indomaret/Alfamart/銀行ATMで引出可。",
    "tips.meals": "食事の価格(目安)",
    "tips.budget": "節約(~IDR 30,000 / 約280円)",
    "tips.budgetDesc": "ワルン(地元食堂)、ナシゴレン、ミーゴレン、パダン料理",
    "tips.moderate": "標準(IDR 50,000–150,000 / 約450~1,400円)",
    "tips.moderateDesc": "中級レストラン、ビーチカフェ、寿司、洋食",
    "tips.luxury": "贅沢(IDR 200,000+ / 1,800円+)",
    "tips.luxuryDesc": "ファインダイニング、ビーチクラブ、バリ/ジャカルタのミシュラン級店",
    "tips.muslim": "ムスリム旅行者へ",
    "tips.muslimDesc": "インドネシアは世界最大のムスリム人口の国。ハラル食は一般的。ショッピングモール、ガソリンスタンド、空港、公共建物に礼拝室(ムショラ)あり。金曜正午の礼拝(12:00)は非観光地で営業が一時停止することも。",
    "tips.weather": "天気",
    "tips.weatherDesc": "通年熱帯気候(26~32°C)。乾季5~9月(ビーチ/登山に最適)。雨季10~4月は短時間の強い雨、主に午後。日の出登山(ブロモ、リンジャニ)は防寒必須 — 高所では5°Cまで下がる。",
    "tips.useful": "便利な情報",
    "tips.bargain": "伝統市場では値切りが普通 — 提示価格の30~50%から開始。",
    "tips.water": "ボトル水か濾過水のみ飲用。非観光地では氷を避ける。",
    "tips.modesty": "寺院/モスク訪問時は肩と膝を覆う。寺院入口でサロンの貸出あり。",
    "tips.tipping": "チップ文化なし — サービス料(5~10%)が請求書に含まれる場合多し。",
    "tips.simcard": "空港でTelkomselかXLのSIM(IDR 100,000 / 20GB・30日)購入。登録にパスポート必要。",
    "tips.emergency": "緊急:112(共通)、110(警察)、118(救急)、119(消防)。",
    "tips.tourist": "観光警察:110で英語対応を依頼。バリ:+62-361-754-599。",
    "tips.korean": "在インドネシア日本国大使館:+62-21-3192-4308(ジャカルタ)。",
    "tips.lastUpdated": "情報は2026年現在 · 出典:インドネシア観光省、各航空会社公式サイト",

    "footer.text": "© 2026 Travel-ID. All rights reserved.",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
  }
};

// Backward compat: expose `zh-CN` and `zh-cn` as aliases of `zh`
translations['zh-CN'] = translations.zh;
translations['zh-cn'] = translations.zh;

if (typeof module !== 'undefined' && module.exports) {
  module.exports = translations;
} else if (typeof window !== 'undefined') {
  window.__TRAVEL_TRANSLATIONS__ = translations;
}
