-- 0003_regional_spots.sql — 56 spots across 7 Indonesian regions
-- Jakarta · Yogyakarta · Malang · Bandung · Medan · Manado · Bogor (8 each).
--
-- GENERATED FILE — edit scripts/regional-spots-data.js then re-run:
--   node scripts/seed-regional-spots.js --emit-sql
--
-- Translations authored for en + id + ko + zh; ms/ja/ar fall back to en in the
-- app (see api/travel-spots.js formatSpot). Idempotent: ON CONFLICT DO NOTHING.

with new_spots as (
  insert into travelid.spots (
    name, category, region, country, latitude, longitude, address,
    halal, prayer_room, entry_fee, best_time_to_visit, local_tips,
    opening_hours, tags, featured, published
  ) values
    ('Kota Tua Jakarta', 'cultural', 'Jakarta', 'ID', -6.1352, 106.8133,
     'Jl. Taman Fatahillah, Pinangsia, Taman Sari, West Jakarta',
     true, true, 0, 'Evening',
     'Rent a colorful colonial bike (IDR 20–50k/30min) on Fatahillah Square. Fatahillah Museum entry IDR 5k. Comes alive at dusk with street performers.',
     'Square 24h; museums Tue–Sun 09:00–15:00',
     array['cultural', 'photogenic', 'family-friendly'], true, true),

    ('National Monument (Monas)', 'cultural', 'Jakarta', 'ID', -6.1754, 106.8272,
     'Gambir, Central Jakarta, DKI Jakarta',
     true, true, 20000, 'Early Morning',
     'Observation deck (132m) ticket ~IDR 20k; queue early on weekends. Flame is gilded with 50kg of gold. Surrounded by Merdeka Square parkland.',
     'Tue–Sun 08:00–22:00 (closed last Mon of month)',
     array['photogenic', 'family-friendly', 'instagram-spot'], true, true),

    ('Istiqlal Mosque', 'mosque', 'Jakarta', 'ID', -6.1699, 106.8307,
     'Jl. Taman Wijaya Kusuma, Ps. Baru, Sawah Besar, Central Jakarta',
     true, true, 0, 'All Year',
     'Largest mosque in Southeast Asia (200k capacity). Free guided tours for non-Muslims; modest dress required (robes lent at entrance). Faces Jakarta Cathedral across the road — a symbol of tolerance.',
     'Daily 04:00–22:00 (outside prayer times for tourists)',
     array['cultural', 'photogenic'], false, true),

    ('Jakarta Cathedral', 'cultural', 'Jakarta', 'ID', -6.1693, 106.8294,
     'Jl. Katedral No.7B, Ps. Baru, Sawah Besar, Central Jakarta',
     false, false, 0, 'All Year',
     'Neo-Gothic cathedral (1901) with twin iron spires. Small museum on the mezzanine. Visit alongside Istiqlal Mosque opposite — the two share a connecting "tunnel of friendship".',
     'Mon–Sat 06:00–18:00; Sun for Mass',
     array['cultural', 'photogenic'], false, true),

    ('National Museum of Indonesia', 'museum', 'Jakarta', 'ID', -6.1764, 106.822,
     'Jl. Medan Merdeka Barat No.12, Gambir, Central Jakarta',
     true, true, 25000, 'All Year',
     'Also called "Museum Gajah" (Elephant Museum) for the bronze elephant out front. Vast collection of prehistoric, Hindu-Buddhist and ethnographic artifacts. Partially reopened after the 2023 fire.',
     'Tue–Sun 08:00–16:00 (closed Mon)',
     array['cultural', 'family-friendly'], false, true),

    ('Ancol Dreamland', 'nature', 'Jakarta', 'ID', -6.123, 106.845,
     'Jl. Lodan Timur No.7, Ancol, Pademangan, North Jakarta',
     true, true, 35000, 'All Year',
     'Sprawling bayfront resort: gate fee ~IDR 35k, then pay-per-park (Dunia Fantasi theme park, SeaWorld, Atlantis Water Adventure). Jakarta''s main public beach — weekends are crowded.',
     'Daily 06:00–22:00',
     array['family-friendly', 'beach'], false, true),

    ('Taman Mini Indonesia Indah', 'cultural', 'Jakarta', 'ID', -6.3024, 106.8951,
     'Jl. Raya Taman Mini, Ceger, Cipayung, East Jakarta',
     true, true, 25000, 'All Year',
     'Culture park showing all 38 provinces in miniature pavilions. Rent a bike/scooter or ride the cable car (Skylift) to see the lake-island archipelago map from above. Recently renovated.',
     'Daily 07:00–22:00',
     array['cultural', 'family-friendly'], false, true),

    ('Glodok Chinatown', 'cultural', 'Jakarta', 'ID', -6.145, 106.8133,
     'Glodok, Tamansari, West Jakarta',
     false, false, 0, 'Early Morning',
     'One of the oldest Chinatowns in the world. Visit Petak Sembilan wet market and Jin De Yuan temple (1650). Famous for kopi es tak kie and street food. Go in the morning before the heat.',
     'Streets all day; market stalls best 07:00–14:00',
     array['cultural', 'food', 'photogenic'], false, true),

    ('Prambanan Temple', 'temple', 'Yogyakarta', 'ID', -7.752, 110.4915,
     'Jl. Raya Solo–Yogyakarta No.16, Kranggan, Bokoharjo, Sleman',
     true, true, 350000, 'Sunset',
     'Foreigner ticket ~IDR 350k (combo with Borobudur ~IDR 650k saves money). Catch the open-air Ramayana Ballet on full-moon nights. Sunset behind the spires is the iconic shot.',
     'Daily 06:30–17:00',
     array['unesco', 'photogenic', 'family-friendly', 'instagram-spot'], true, true),

    ('Malioboro Street', 'shopping', 'Yogyakarta', 'ID', -7.7926, 110.3656,
     'Jl. Malioboro, Sosromenduran, Gedongtengen, Yogyakarta City',
     true, true, 0, 'Evening',
     'Yogya''s main pedestrian boulevard. Bargain hard for batik and silver. Try lesehan (sit-on-mat) gudeg stalls at night. The street links the Tugu monument to the Kraton.',
     'Shops 09:00–21:00; night stalls until late',
     array['shopping', 'food', 'family-friendly'], false, true),

    ('Kraton Yogyakarta (Sultan''s Palace)', 'cultural', 'Yogyakarta', 'ID', -7.8053, 110.3642,
     'Jl. Rotowijayan Blok No.1, Panembahan, Kraton, Yogyakarta City',
     true, true, 15000, 'Early Morning',
     'Still the living residence of the Sultan. Entry IDR 15k + small camera fee. Catch free gamelan, wayang or classical dance performances on scheduled mornings. Hire a palace guide for the history.',
     'Daily 09:00–14:00 (Fri until 11:00)',
     array['cultural', 'photogenic'], false, true),

    ('Taman Sari Water Castle', 'cultural', 'Yogyakarta', 'ID', -7.8101, 110.359,
     'Jl. Tamanan, Patehan, Kraton, Yogyakarta City',
     true, false, 15000, 'Early Morning',
     'Former royal bathing and pleasure garden (1758). Don''t miss the underground mosque (Sumur Gumuling) with its photogenic stairways. Local guides wait at the entrance (~IDR 50k).',
     'Daily 09:00–15:00',
     array['cultural', 'photogenic', 'instagram-spot'], false, true),

    ('Tugu Yogyakarta', 'cultural', 'Yogyakarta', 'ID', -7.7828, 110.3671,
     'Jl. Jenderal Sudirman, Gowongan, Jetis, Yogyakarta City',
     true, false, 0, 'Evening',
     'The white-and-gold pillar is Yogya''s emblem and a rite-of-passage photo spot for students. Best after dark when lit. Roads are busy — cross with care for the centered shot.',
     'Open 24h (viewed from outside)',
     array['photogenic', 'instagram-spot'], false, true),

    ('Parangtritis Beach', 'beach', 'Yogyakarta', 'ID', -8.0257, 110.3289,
     'Parangtritis, Kretek, Bantul Regency, Yogyakarta',
     true, true, 10000, 'Sunset',
     'Famous black-sand beach ~27km south of the city. Strong currents — swimming is dangerous; enjoy the sand dunes, horse carts and paragliding instead. Linked to the Queen of the Southern Sea legend (don''t wear green).',
     'Open 24h (sunset best)',
     array['beach', 'photogenic', 'instagram-spot'], false, true),

    ('Jomblang Cave', 'adventure', 'Yogyakarta', 'ID', -8.0289, 110.6383,
     'Jetis Wetan, Pacarejo, Semanu, Gunungkidul Regency',
     true, false, 500000, 'Early Morning',
     'Vertical caving: you are rappelled 60m down into an ancient collapsed doline. Around 10:00 a "ray of heaven" sunbeam pierces the cave. Book ahead (~IDR 500k incl. gear); arrive before noon for the light.',
     'By booking, ~08:00–12:00 slots',
     array['adventure', 'hidden-gem', 'photogenic', 'instagram-spot'], false, true),

    ('Kotagede Silver Quarter', 'cultural', 'Yogyakarta', 'ID', -7.8267, 110.3997,
     'Kotagede, Yogyakarta City',
     true, true, 0, 'All Year',
     'The former capital of the Mataram Sultanate, now Yogya''s silver-craft hub. Watch artisans at work and join a silversmithing workshop. Wander the old alleyways and the historic royal cemetery.',
     'Workshops 09:00–17:00',
     array['cultural', 'shopping', 'hidden-gem'], false, true),

    ('Museum Angkut', 'museum', 'Malang', 'ID', -7.8806, 112.5237,
     'Jl. Terusan Sultan Agung No.2, Ngaglik, Batu City',
     true, true, 120000, 'All Year',
     'Southeast Asia''s first transport museum, in cool-climate Batu. Themed zones (Hollywood, Europe, Jakarta old town) packed with vintage cars and planes. Weekday tickets cheaper; go for the evening lights.',
     'Daily 12:00–20:00',
     array['family-friendly', 'photogenic', 'instagram-spot'], true, true),

    ('Coban Rondo Waterfall', 'nature', 'Malang', 'ID', -7.8869, 112.4727,
     'Pandesari, Pujon, Malang Regency',
     true, true, 30000, 'All Year',
     '84m waterfall in the Pujon highlands, ~1.5h from Malang. Cool mountain air; bring a light jacket. Easy paved path, labyrinth garden and a paralayang (paragliding) hill nearby.',
     'Daily 08:00–17:00',
     array['nature', 'family-friendly', 'photogenic'], false, true),

    ('Alun-Alun Tugu Malang', 'cultural', 'Malang', 'ID', -7.9785, 112.6308,
     'Jl. Tugu, Kiduldalem, Klojen, Malang City',
     true, true, 0, 'Evening',
     'The colonial-era civic square in front of Malang''s grand old city hall, ringed by heritage buildings and a lotus pond. Lovely at dusk. Combine with a walk down nearby Jalan Ijen''s art-deco mansions.',
     'Open 24h',
     array['cultural', 'photogenic', 'family-friendly'], false, true),

    ('Jodipan Colorful Village', 'cultural', 'Malang', 'ID', -7.992, 112.633,
     'Jodipan, Blimbing, Malang City',
     true, false, 5000, 'All Year',
     'A former slum on the riverbank transformed into a rainbow of painted houses and murals. Tiny entry fee includes a postcard. Narrow lanes and glass bridge — great for photos but respect that people live here.',
     'Daily 08:00–17:00',
     array['photogenic', 'instagram-spot', 'cultural'], false, true),

    ('Batu Secret Zoo', 'nature', 'Malang', 'ID', -7.885, 112.526,
     'Jl. Oro-Oro Ombo No.9, Temas, Batu City (Jatim Park 2)',
     true, true, 130000, 'All Year',
     'Modern zoo inside the Jatim Park 2 complex with open enclosures, a tiger and fancy aquarium. Combo tickets with the Animal Museum. Plan 3–4 hours; weekdays are far quieter.',
     'Daily 10:00–18:00',
     array['family-friendly', 'nature'], false, true),

    ('Selecta Recreational Park', 'nature', 'Malang', 'ID', -7.8146, 112.5267,
     'Jl. Raya Selecta No.1, Tulungrejo, Bumiaji, Batu City',
     true, true, 45000, 'All Year',
     'Indonesia''s oldest flower park (since 1930), on the slopes of Mount Arjuno. Terraced flower gardens, a cold-spring swimming pool and apple orchards. Crisp mountain weather — pack a jacket.',
     'Daily 07:00–18:00',
     array['family-friendly', 'nature', 'photogenic'], false, true),

    ('Balekambang Beach', 'beach', 'Malang', 'ID', -8.3997, 112.534,
     'Srigonco, Bantur, Malang Regency',
     true, true, 25000, 'Sunset',
     'Often called "Tanah Lot of East Java" — a Hindu temple sits on an offshore islet linked by a footbridge. ~2.5h south of Malang on winding roads; combine with nearby beaches for a day trip.',
     'Open 24h (daytime best)',
     array['beach', 'temple', 'photogenic'], false, true),

    ('Coban Pelangi Waterfall', 'nature', 'Malang', 'ID', -7.9772, 112.887,
     'Gubugklakah, Poncokusumo, Malang Regency',
     true, true, 25000, 'All Year',
     '"Rainbow Waterfall" — on sunny late mornings a rainbow forms in the spray. On the road to Bromo, so easy to combine. 15-min downhill forest trek each way; wear grippy shoes.',
     'Daily 07:00–16:00',
     array['nature', 'adventure', 'hidden-gem'], false, true),

    ('Tangkuban Perahu', 'volcano', 'Bandung', 'ID', -6.7599, 107.6098,
     'Cikole, Lembang, West Bandung Regency',
     true, true, 200000, 'Early Morning',
     'Drive-up volcano with a vast steaming crater (Kawah Ratu). Foreigner ticket pricier on weekends. Go early before clouds/crowds; sulphur smell is strong. Vendors sell strawberries and grilled corn at the rim.',
     'Daily 07:00–17:00',
     array['volcano', 'photogenic', 'family-friendly', 'instagram-spot'], true, true),

    ('Kawah Putih (White Crater)', 'nature', 'Bandung', 'ID', -7.166, 107.4022,
     'Sugihmukti, Pasirjambu, Bandung Regency',
     true, true, 76000, 'All Year',
     'Surreal pale-turquoise sulphur crater lake south of Bandung. Park then take the shuttle (ontang-anting) up. Colour shifts with weather; arrive 08:00–10:00 for the clearest water. A mask helps with sulphur fumes.',
     'Daily 07:00–17:00',
     array['nature', 'photogenic', 'instagram-spot'], true, true),

    ('Gedung Sate', 'cultural', 'Bandung', 'ID', -6.9025, 107.619,
     'Jl. Diponegoro No.22, Citarum, Bandung Wetan, Bandung City',
     true, true, 5000, 'All Year',
     'West Java''s art-deco government palace (1920), named for the satay-skewer ornament on its central spire. The basement Gedung Sate Museum is interactive and cheap. The lawn is a popular weekend gathering spot.',
     'Museum Tue–Sun 09:30–16:00',
     array['cultural', 'photogenic'], false, true),

    ('Floating Market Lembang', 'cultural', 'Bandung', 'ID', -6.8168, 107.6175,
     'Jl. Grand Hotel No.33E, Lembang, West Bandung Regency',
     true, true, 30000, 'All Year',
     'Lakeside food market where vendors sell Sundanese snacks from boats — pay with wooden tokens. Cool Lembang weather, mini theme zones (rabbit park, mini-train) make it family-friendly. Entry fee redeemable for drinks.',
     'Daily 09:00–17:00 (Fri–Sun later)',
     array['food', 'family-friendly', 'photogenic'], false, true),

    ('Dusun Bambu', 'nature', 'Bandung', 'ID', -6.7889, 107.5772,
     'Jl. Kolonel Masturi KM.11, Cisarua, West Bandung Regency',
     true, true, 35000, 'All Year',
     'Eco-resort and family leisure park in bamboo forest. Famous for nest-shaped dining cabins (Lutung Kasarung) overlooking a lake. Cool air, flower gardens and lake boats. Entry credit can be spent on food.',
     'Daily 09:00–20:00',
     array['nature', 'cafe', 'family-friendly', 'photogenic'], false, true),

    ('Trans Studio Bandung', 'adventure', 'Bandung', 'ID', -6.9258, 107.636,
     'Jl. Gatot Subroto No.289, Cibangkong, Batununggal, Bandung City',
     true, true, 280000, 'All Year',
     'One of the world''s largest indoor theme parks — air-conditioned, so weather-proof. ~20 rides including a steep coaster and 4D cinema. Buy a cashless megacard at the gate. Linked to a mall and hotel.',
     'Daily 10:00–18:00 (weekends later)',
     array['family-friendly', 'adventure'], false, true),

    ('Farmhouse Lembang', 'cafe', 'Bandung', 'ID', -6.833, 107.606,
     'Jl. Raya Lembang No.108, Cihideung, Bandung Barat',
     true, true, 35000, 'All Year',
     'European-village-themed park with a fairytale hobbit house, a small petting zoo and costume rentals. Entry ticket redeemable for milk or sausage. Very popular and crowded on weekends — go on a weekday.',
     'Daily 09:00–20:00',
     array['cafe', 'photogenic', 'instagram-spot', 'family-friendly'], false, true),

    ('Jalan Braga', 'cultural', 'Bandung', 'ID', -6.9175, 107.6094,
     'Braga, Sumur Bandung, Bandung City',
     true, false, 0, 'Evening',
     'The art-deco heart of "Paris van Java", once Bandung''s most fashionable promenade. Cobblestone street of vintage cafes, galleries and colonial facades. Best in the evening; live music spills out of bars.',
     'Cafes 10:00–22:00',
     array['cultural', 'cafe', 'photogenic'], false, true),

    ('Maimun Palace', 'cultural', 'Medan', 'ID', 3.5752, 98.6837,
     'Jl. Brigjen Katamso, Aur, Medan Maimun, Medan City',
     true, true, 10000, 'All Year',
     'The 1888 palace of the Sultanate of Deli, blending Malay, Mughal, Italian and Dutch styles. Rent Malay costume for photos on the throne. Cheap entry; the main hall is the highlight.',
     'Daily 08:00–17:00',
     array['cultural', 'photogenic'], false, true),

    ('Great Mosque of Medan (Al-Mashun)', 'mosque', 'Medan', 'ID', 3.5793, 98.6873,
     'Jl. Sisingamangaraja, Mesjid, Medan Kota, Medan City',
     true, true, 0, 'All Year',
     'The grand mosque of Medan (1909), built by the Deli Sultanate in Moroccan-Mughal style with octagonal Italian marble halls. Donation entry; dress modestly. A short walk from Maimun Palace.',
     'Daily, outside prayer times for visitors',
     array['cultural', 'photogenic'], false, true),

    ('Lake Toba', 'nature', 'Medan', 'ID', 2.6845, 98.9214,
     'Parapat, Girsang Sipangan Bolon, Simalungun Regency, North Sumatra',
     true, true, 0, 'Dry Season (May-Sep)',
     'The world''s largest volcanic lake, ~4h from Medan. Take the ferry from Parapat to Samosir Island (Tuk Tuk) — the Batak cultural heartland. Cool climate; stay 2+ nights to relax lakeside.',
     'Open 24h (ferries daytime)',
     array['nature', 'photogenic', 'family-friendly', 'instagram-spot'], true, true),

    ('Tjong A Fie Mansion', 'cultural', 'Medan', 'ID', 3.5859, 98.679,
     'Jl. Ahmad Yani No.105, Kesawan, Medan Barat, Medan City',
     false, false, 35000, 'All Year',
     'The 1900 mansion of a Hakka Chinese tycoon and philanthropist, blending Chinese, Malay and art-deco styles. Guided ticket includes the family history. In the historic Kesawan colonial district.',
     'Daily 09:00–17:00',
     array['cultural', 'photogenic', 'hidden-gem'], false, true),

    ('Samosir Island', 'nature', 'Medan', 'ID', 2.5833, 98.8333,
     'Samosir Regency, Lake Toba, North Sumatra',
     true, true, 0, 'Dry Season (May-Sep)',
     'A volcanic island inside Lake Toba, nearly the size of Singapore — the Batak homeland. Base yourself in Tuk Tuk. See Batak king tombs at Tomok, stone chairs at Ambarita, and rent a scooter to circle the island.',
     'Open 24h (ferries daytime)',
     array['nature', 'cultural', 'photogenic'], false, true),

    ('Berastagi Highland', 'nature', 'Medan', 'ID', 3.1953, 98.5103,
     'Berastagi, Karo Regency, North Sumatra',
     true, true, 0, 'Dry Season (May-Sep)',
     'Cool Karo highland town ~2h from Medan, ringed by the Sibayak and Sinabung volcanoes. Climb Sibayak at dawn, soak in hot springs, and browse the famous fruit & flower market. Pack warm layers.',
     'Open 24h',
     array['nature', 'adventure', 'volcano'], false, true),

    ('Graha Maria Annai Velangkanni', 'cultural', 'Medan', 'ID', 3.538, 98.647,
     'Jl. Sakura III No.7, Tanjung Selamat, Medan Tuntungan, Medan City',
     false, false, 0, 'All Year',
     'A unique Indo-Mughal style Catholic church honoring Our Lady of Velankanni — looks more like a temple than a church. Seven-storey tower; quiet and free to visit. Modest dress appreciated.',
     'Daily 08:00–17:00',
     array['cultural', 'photogenic', 'hidden-gem'], false, true),

    ('Rahmat International Wildlife Museum', 'museum', 'Medan', 'ID', 3.568, 98.652,
     'Jl. S. Parman No.309, Petisah Tengah, Medan Petisah, Medan City',
     true, true, 50000, 'All Year',
     'One of Asia''s largest taxidermy/diorama wildlife museums — hundreds of mounted species in lifelike habitat scenes. Educational and air-conditioned; good for kids on a hot Medan afternoon.',
     'Daily 09:00–17:00',
     array['museum', 'family-friendly'], false, true),

    ('Bunaken National Marine Park', 'diving', 'Manado', 'ID', 1.6206, 124.7595,
     'Bunaken Island, Manado Tua, Manado City, North Sulawesi',
     true, true, 150000, 'Dry Season (May-Sep)',
     'World-class diving with sheer coral walls dropping 1,000m+ and huge biodiversity. Marine-park fee ~IDR 150k. Best visibility May–Oct. Snorkellers can reach the reef edge from the beach; turtles common.',
     'Daytime; dive trips from Manado',
     array['diving', 'nature', 'hidden-gem', 'photogenic'], true, true),

    ('Mount Lokon', 'volcano', 'Manado', 'ID', 1.358, 124.792,
     'Tomohon, North Sulawesi',
     true, true, 50000, 'Early Morning',
     'An active 1,580m volcano above Tomohon with a smoking crater (Tompaluan). Check the alert status before climbing — access is sometimes restricted. Early start for views over the city and sea. Hire a local guide.',
     'Dawn climbs; check volcanic activity status',
     array['volcano', 'adventure', 'hidden-gem'], false, true),

    ('Tangkoko Nature Reserve', 'nature', 'Manado', 'ID', 1.5483, 125.19,
     'Batuputih, Ranowulu, Bitung, North Sulawesi',
     true, true, 100000, 'Early Morning',
     'Coastal rainforest reserve famous for the tiny tarsier (world''s smallest primate) and black-crested macaques. A mandatory guide finds wildlife at dawn or dusk. ~2h from Manado near Bitung.',
     'Guided treks dawn & late afternoon',
     array['nature', 'hidden-gem', 'photogenic', 'adventure'], true, true),

    ('Christ Blessing Statue', 'cultural', 'Manado', 'ID', 1.4407, 124.829,
     'Citraland, Winangun, Malalayang, Manado City',
     false, false, 0, 'Sunset',
     'A 50m statue of Jesus on a hill in the Citraland estate, leaning forward as if flying — one of the tallest Christ statues in Asia. Free to view from the base; best at sunset over Manado.',
     'Viewed from roadside / Citraland',
     array['cultural', 'photogenic', 'instagram-spot'], false, true),

    ('Lake Linow', 'nature', 'Manado', 'ID', 1.3145, 124.829,
     'Lahendong, Tomohon Selatan, Tomohon, North Sulawesi',
     true, true, 50000, 'All Year',
     'A sulphur crater lake near Tomohon that shifts colour — turquoise, green, amber — with the light and sulphur content. Lakeside cafes serve coffee with the view. Entry includes a drink.',
     'Daily 08:00–18:00',
     array['nature', 'photogenic', 'cafe'], false, true),

    ('Bukit Kasih Kanonang', 'cultural', 'Manado', 'ID', 1.273, 124.743,
     'Kanonang, Kawangkoan Barat, Minahasa Regency, North Sulawesi',
     true, true, 20000, 'All Year',
     '"Hill of Love" — a volcanic hill of religious tolerance with five houses of worship (mosque, church, temples) and a tall white cross reached by a long stairway. Sulphur vents steam nearby. Bring water.',
     'Daily 08:00–17:00',
     array['cultural', 'photogenic', 'hidden-gem'], false, true),

    ('Siladen Island', 'beach', 'Manado', 'ID', 1.6447, 124.8186,
     'Siladen Island, Bunaken National Park, Manado City',
     true, true, 150000, 'Dry Season (May-Sep)',
     'A tiny white-sand island within Bunaken park, quieter than Bunaken itself. Excellent house-reef snorkelling straight off the beach. Day trip or stay at an eco-resort. Same marine-park fee applies.',
     'Daytime; boats from Manado',
     array['beach', 'diving', 'hidden-gem', 'photogenic'], false, true),

    ('Mount Mahawu', 'volcano', 'Manado', 'ID', 1.3585, 124.865,
     'Tomohon, North Sulawesi',
     true, false, 25000, 'Early Morning',
     'An easy volcano near Tomohon — a 15-min stair climb reaches the crater rim with a green crater lake and views to Lokon and the sea. Far gentler than Lokon, good for families. Cool and breezy; bring a jacket.',
     'Daylight; best at dawn',
     array['volcano', 'adventure', 'photogenic'], false, true),

    ('Bogor Botanical Gardens', 'nature', 'Bogor', 'ID', -6.5979, 106.798,
     'Jl. Ir. H. Juanda No.13, Paledang, Bogor Tengah, Bogor City',
     true, true, 25000, 'All Year',
     'Founded 1817, these 87-hectare gardens hold 15,000+ plant species, giant rainforest trees, an orchid house and the giant Amorphophallus. Cool morning air; rent a bike or e-cart. Surrounds the Presidential Palace.',
     'Daily 08:00–16:00',
     array['nature', 'family-friendly', 'photogenic'], true, true),

    ('Taman Safari Indonesia', 'nature', 'Bogor', 'ID', -6.7203, 106.9497,
     'Jl. Kapten Harun Kabir No.724, Cibeureum, Cisarua, Bogor Regency',
     true, true, 230000, 'All Year',
     'Drive-through safari in the cool Puncak hills where animals roam free around your car — buy carrots to feed deer and zebras. Also a walking zoo, shows and rides. Go early; the Puncak road jams up by midday.',
     'Daily 09:00–17:00 (night safari weekends)',
     array['family-friendly', 'nature'], false, true),

    ('Bogor Palace', 'cultural', 'Bogor', 'ID', -6.597, 106.7969,
     'Jl. Ir. H. Juanda No.1, Paledang, Bogor Tengah, Bogor City',
     true, true, 0, 'All Year',
     'A colonial-era state palace inside the Botanical Gardens, famous for the herd of spotted deer grazing its lawns (visible from the garden fence). Interior visits need an advance permit; most just admire the deer.',
     'Group tours by prior permit only',
     array['cultural', 'photogenic'], false, true),

    ('Gunung Pancar Hot Springs', 'nature', 'Bogor', 'ID', -6.565, 106.918,
     'Karang Tengah, Babakan Madang, Bogor Regency',
     true, true, 30000, 'All Year',
     'A pine-forest park with natural hot-spring pools northeast of Bogor. Shady photogenic pine groves, camping and soaking pools. 4WD/ojek recommended for the last rough stretch. Cool and quiet on weekdays.',
     'Daily 07:00–17:00',
     array['nature', 'wellness', 'photogenic'], false, true),

    ('Puncak Pass', 'nature', 'Bogor', 'ID', -6.701, 106.99,
     'Puncak, Cisarua, Bogor Regency',
     true, true, 0, 'Early Morning',
     'The breezy mountain pass between Bogor and Cianjur, famous for rolling Gunung Mas tea plantations and cool air. Photograph the green terraces, sip estate tea, try paragliding. Go early — the road jams on weekends.',
     'Open 24h (tea estates daytime)',
     array['nature', 'cafe', 'photogenic'], false, true),

    ('Curug Cilember Waterfall', 'nature', 'Bogor', 'ID', -6.673, 106.927,
     'Jogjogan, Cisarua, Bogor Regency',
     true, true, 25000, 'All Year',
     'A series of seven tiered waterfalls in the Puncak pine forest. The lowest (Curug 7) is an easy walk; higher tiers need a hike. There''s also a butterfly conservatory and camping. Cool, often misty.',
     'Daily 08:00–17:00',
     array['nature', 'family-friendly', 'hidden-gem'], false, true),

    ('The Jungle Waterpark', 'adventure', 'Bogor', 'ID', -6.636, 106.815,
     'Bogor Nirwana Residence, Jl. Bogor Nirwana Boulevard, Mulyaharja, Bogor City',
     true, true, 90000, 'All Year',
     'A large family water park on the south side of Bogor with wave pools, slides and a 4D cinema, backed by mountain views. Quieter on weekdays. Bring your own towel; lockers available.',
     'Daily 09:00–18:00',
     array['family-friendly', 'adventure'], false, true),

    ('Devoyage Bogor', 'cultural', 'Bogor', 'ID', -6.541, 106.809,
     'Jl. Sukasari II No.3, Bantarjati, Bogor Utara, Bogor City',
     true, true, 50000, 'All Year',
     'A photo-themed park recreating world landmarks — Santorini alleys, Moroccan doors, Japanese lanes. Built purely for Instagram. Costume rental available. Best in late afternoon light; lit up after dark.',
     'Daily 09:00–20:00',
     array['photogenic', 'instagram-spot', 'family-friendly'], false, true)
  on conflict ((lower(name))) do nothing
  returning id, name
)
insert into travelid.spot_translations (spot_id, lang, name, description)
select id, t.lang, t.name, t.description
from new_spots
join lateral (values
  ('Kota Tua Jakarta', 'en', 'Kota Tua Jakarta', 'The old Batavia colonial quarter: Dutch-era warehouses, cobbled Fatahillah Square, the Jakarta History Museum and Wayang (puppet) Museum clustered together.'),
  ('Kota Tua Jakarta', 'id', 'Kota Tua Jakarta', 'Kawasan kolonial Batavia lama: gudang era Belanda, Taman Fatahillah berbatu, Museum Sejarah Jakarta dan Museum Wayang.'),
  ('Kota Tua Jakarta', 'ko', '자카르타 코타투아 (구시가지)', '바타비아 식민지 시대 구역. 네덜란드풍 창고, 파타힐라 광장, 자카르타 역사박물관과 와양(인형) 박물관이 모여 있다.'),
  ('Kota Tua Jakarta', 'zh', '雅加达老城区', '巴达维亚殖民时期老城区:荷兰时代仓库、法塔希拉广场、雅加达历史博物馆与皮影戏博物馆。'),
  ('National Monument (Monas)', 'en', 'National Monument (Monas)', '132m marble obelisk in Merdeka Square topped by a gold-leaf flame — the symbol of Indonesian independence, with an observation deck and a diorama history museum at the base.'),
  ('National Monument (Monas)', 'id', 'Monumen Nasional (Monas)', 'Obelisk marmer 132m di Lapangan Merdeka dengan lidah api berlapis emas — simbol kemerdekaan Indonesia, ada dek observasi dan museum diorama.'),
  ('National Monument (Monas)', 'ko', '독립기념탑 (모나스)', '메르데카 광장에 선 132m 대리석 오벨리스크. 금박 불꽃이 정상을 장식하는 인도네시아 독립의 상징으로, 전망대와 디오라마 역사관이 있다.'),
  ('National Monument (Monas)', 'zh', '国家纪念塔(Monas)', '独立广场上132米高的大理石方尖碑,顶端为金箔火炬,是印尼独立的象征,设有观景台和立体模型历史馆。'),
  ('Istiqlal Mosque', 'en', 'Istiqlal Mosque', 'The national mosque of Indonesia and the largest in Southeast Asia, holding up to 200,000 worshippers. Its modernist steel-and-marble design stands directly opposite Jakarta Cathedral.'),
  ('Istiqlal Mosque', 'id', 'Masjid Istiqlal', 'Masjid nasional Indonesia dan terbesar di Asia Tenggara, menampung 200.000 jamaah. Desain modernis baja-marmer, berhadapan dengan Katedral Jakarta.'),
  ('Istiqlal Mosque', 'ko', '이스티크랄 모스크', '인도네시아 국립 모스크이자 동남아 최대 규모(20만 명 수용). 강철·대리석의 모더니즘 건축으로, 길 건너 자카르타 대성당과 마주보고 있다.'),
  ('Istiqlal Mosque', 'zh', '伊斯蒂克拉尔清真寺', '印尼国家清真寺,东南亚最大,可容纳20万人。钢与大理石的现代主义建筑,与雅加达大教堂隔街相望。'),
  ('Jakarta Cathedral', 'en', 'Jakarta Cathedral', 'A neo-Gothic Roman Catholic cathedral completed in 1901, with twin cast-iron spires. Stands opposite Istiqlal Mosque as a celebrated symbol of Indonesia''s religious harmony.'),
  ('Jakarta Cathedral', 'id', 'Katedral Jakarta', 'Katedral Katolik bergaya neo-Gotik selesai 1901 dengan dua menara besi. Berdiri di hadapan Masjid Istiqlal sebagai simbol kerukunan beragama Indonesia.'),
  ('Jakarta Cathedral', 'ko', '자카르타 대성당', '1901년 완공된 네오고딕 양식의 가톨릭 대성당. 쌍둥이 주철 첨탑이 특징이며, 이스티크랄 모스크와 마주보아 종교 화합의 상징으로 꼽힌다.'),
  ('Jakarta Cathedral', 'zh', '雅加达大教堂', '1901年建成的新哥特式天主教堂,有两座铸铁尖塔。与伊斯蒂克拉尔清真寺相对而立,象征印尼宗教和谐。'),
  ('National Museum of Indonesia', 'en', 'National Museum of Indonesia', 'Indonesia''s premier museum (the "Elephant Museum"), holding the country''s richest collection of archaeological, ethnographic and Hindu-Buddhist statuary across the archipelago.'),
  ('National Museum of Indonesia', 'id', 'Museum Nasional Indonesia', 'Museum utama Indonesia ("Museum Gajah"), menyimpan koleksi arkeologi, etnografi dan arca Hindu-Buddha terkaya dari seluruh nusantara.'),
  ('National Museum of Indonesia', 'ko', '인도네시아 국립박물관', '코끼리 동상으로 "가자 박물관"이라 불리는 인도네시아 대표 박물관. 군도 전역의 고고학·민족지·힌두불교 조각 컬렉션을 소장한다.'),
  ('National Museum of Indonesia', 'zh', '印度尼西亚国家博物馆', '俗称"大象博物馆",印尼最重要的博物馆,藏有全国最丰富的考古、民族志及印度教-佛教雕像。'),
  ('Ancol Dreamland', 'en', 'Ancol Dreamland', 'A huge bayfront recreation complex on Jakarta Bay with theme parks (Dunia Fantasi), SeaWorld, water parks and the city''s most popular public beach.'),
  ('Ancol Dreamland', 'id', 'Taman Impian Jaya Ancol', 'Kompleks rekreasi tepi pantai raksasa di Teluk Jakarta dengan taman hiburan (Dunia Fantasi), SeaWorld, taman air, dan pantai publik terpopuler.'),
  ('Ancol Dreamland', 'ko', '안쫄 드림랜드', '자카르타 만에 자리한 대형 해변 리조트 단지. 두니아 판타지 테마파크, 씨월드, 워터파크와 시내 최고 인기 공공 해변을 갖췄다.'),
  ('Ancol Dreamland', 'zh', '安佐尔梦幻世界', '雅加达湾畔的大型海滨度假区,设有梦幻世界主题乐园、海洋世界、水上乐园及市区最热门的公共海滩。'),
  ('Taman Mini Indonesia Indah', 'en', 'Taman Mini Indonesia Indah', 'A 150-hectare cultural park presenting all of Indonesia''s provinces in traditional-house pavilions, with museums, a cable car and a lake shaped like the Indonesian archipelago.'),
  ('Taman Mini Indonesia Indah', 'id', 'Taman Mini Indonesia Indah', 'Taman budaya 150 hektar yang menampilkan seluruh provinsi Indonesia dalam anjungan rumah adat, dengan museum, kereta gantung, dan danau berbentuk peta nusantara.'),
  ('Taman Mini Indonesia Indah', 'ko', '따만 미니 인도네시아 인다', '150헥타르 규모 문화 공원. 전통 가옥 전시관으로 인도네시아 전 주(州)를 재현하며, 박물관·케이블카·군도 모양 호수를 갖췄다.'),
  ('Taman Mini Indonesia Indah', 'zh', '印度尼西亚缩影公园', '占地150公顷的文化公园,以传统民居展馆呈现印尼各省,设有博物馆、缆车及形似印尼群岛的湖泊。'),
  ('Glodok Chinatown', 'en', 'Glodok Chinatown', 'Jakarta''s historic Chinatown around Petak Sembilan market, packed with century-old temples (Jin De Yuan), herbal shops, traditional bakeries and legendary street-food stalls.'),
  ('Glodok Chinatown', 'id', 'Pecinan Glodok', 'Pecinan bersejarah Jakarta di sekitar pasar Petak Sembilan, penuh kelenteng tua (Jin De Yuan), toko herbal, dan jajanan kaki lima legendaris.'),
  ('Glodok Chinatown', 'ko', '글로독 차이나타운', '뻐딱 슴빌란 시장을 중심으로 한 자카르타 역사 차이나타운. 수백 년 된 사원(진더위안), 한약방, 전통 빵집과 전설적인 길거리 음식이 가득하다.'),
  ('Glodok Chinatown', 'zh', '草埔(Glodok)唐人街', '雅加达历史悠久的唐人街,围绕Petak Sembilan市场,遍布百年古庙(金德院)、药材店与传奇街头美食。'),
  ('Prambanan Temple', 'en', 'Prambanan Temple', 'The largest Hindu temple complex in Indonesia (9th century), a UNESCO World Heritage site. Towering spires dedicated to Shiva, Vishnu and Brahma, with Ramayana relief panels and a famous evening ballet.'),
  ('Prambanan Temple', 'id', 'Candi Prambanan', 'Kompleks candi Hindu terbesar di Indonesia (abad ke-9), Warisan Dunia UNESCO. Menara menjulang untuk Siwa, Wisnu dan Brahma, dengan relief Ramayana dan sendratari malam.'),
  ('Prambanan Temple', 'ko', '프람바난 사원', '인도네시아 최대 힌두 사원 단지(9세기)로 유네스코 세계유산. 시바·비슈누·브라흐마를 모신 높은 첨탑과 라마야나 부조, 저녁 발레 공연으로 유명하다.'),
  ('Prambanan Temple', 'zh', '普兰巴南神庙', '印尼最大的印度教神庙群(9世纪),联合国教科文组织世界遗产。供奉湿婆、毗湿奴和梵天的高耸塔尖,有罗摩衍那浮雕和著名的夜间芭蕾舞剧。'),
  ('Malioboro Street', 'en', 'Malioboro Street', 'The vibrant heart of Yogyakarta — a pedestrian shopping street running from Tugu monument to the Sultan''s Palace, lined with batik stalls, street buskers and nighttime gudeg eateries.'),
  ('Malioboro Street', 'id', 'Jalan Malioboro', 'Jantung Yogyakarta yang ramai — jalan belanja pejalan kaki dari Tugu ke Keraton, dipenuhi lapak batik, pengamen, dan warung gudeg malam.'),
  ('Malioboro Street', 'ko', '말리오보로 거리', '족자카르타의 활기찬 중심가. 투구 기념탑에서 술탄 궁까지 이어지는 보행자 쇼핑 거리로, 바틱 노점·거리 공연·밤의 구득 식당이 늘어서 있다.'),
  ('Malioboro Street', 'zh', '马里奥波罗大街', '日惹热闹的核心步行购物街,从独立纪念碑延伸至苏丹王宫,沿街是蜡染摊位、街头艺人和夜间古德传统餐摊。'),
  ('Kraton Yogyakarta (Sultan''s Palace)', 'en', 'Kraton Yogyakarta (Sultan''s Palace)', 'The walled royal palace of the Yogyakarta Sultanate, still the Sultan''s residence. Pavilions of Javanese architecture, royal heirlooms, and daily gamelan and classical dance performances.'),
  ('Kraton Yogyakarta (Sultan''s Palace)', 'id', 'Keraton Yogyakarta', 'Istana berbenteng Kesultanan Yogyakarta, masih kediaman Sultan. Bangsal arsitektur Jawa, pusaka kerajaan, serta pertunjukan gamelan dan tari klasik harian.'),
  ('Kraton Yogyakarta (Sultan''s Palace)', 'ko', '크라톤 욕야카르타 (술탄 궁)', '욕야카르타 술탄국의 성벽 왕궁으로 지금도 술탄이 거주한다. 자바 건축 양식의 정자, 왕실 보물, 매일 열리는 가믈란·고전 무용 공연을 볼 수 있다.'),
  ('Kraton Yogyakarta (Sultan''s Palace)', 'zh', '日惹苏丹王宫', '日惹苏丹国的城墙王宫,至今仍是苏丹居所。爪哇式建筑亭阁、王室珍宝,以及每日的甘美兰演奏和古典舞表演。'),
  ('Taman Sari Water Castle', 'en', 'Taman Sari Water Castle', 'An 18th-century royal water garden of bathing pools, tunnels and a striking circular underground mosque (Sumur Gumuling) — once the pleasure retreat of the Yogyakarta Sultans.'),
  ('Taman Sari Water Castle', 'id', 'Taman Sari', 'Taman air kerajaan abad ke-18 berupa kolam pemandian, lorong, dan masjid bawah tanah melingkar (Sumur Gumuling) — dulu tempat peristirahatan Sultan Yogyakarta.'),
  ('Taman Sari Water Castle', 'ko', '따만 사리 물의 궁전', '18세기 왕실 물의 정원. 목욕탕과 터널, 인상적인 원형 지하 모스크(수무르 구물링)로 이루어진 욕야카르타 술탄의 옛 휴양처다.'),
  ('Taman Sari Water Castle', 'zh', '水之宫(Taman Sari)', '18世纪王室水上花园,有浴池、地道和别致的圆形地下清真寺(Sumur Gumuling),昔日是日惹苏丹的休憩之所。'),
  ('Tugu Yogyakarta', 'en', 'Tugu Yogyakarta', 'The iconic white pillar marking the symbolic axis between the Sultan''s Palace, Mount Merapi and the southern sea — Yogyakarta''s most photographed landmark, especially when lit at night.'),
  ('Tugu Yogyakarta', 'id', 'Tugu Yogyakarta', 'Tugu putih ikonik yang menandai sumbu filosofis antara Keraton, Gunung Merapi, dan laut selatan — landmark paling difoto di Yogyakarta, terutama saat malam.'),
  ('Tugu Yogyakarta', 'ko', '투구 욕야카르타', '술탄 궁·메라피 화산·남쪽 바다를 잇는 상징 축을 표시하는 흰 기둥. 특히 밤에 조명이 켜질 때 욕야카르타에서 가장 많이 촬영되는 랜드마크다.'),
  ('Tugu Yogyakarta', 'zh', '日惹独立纪念柱', '标志苏丹王宫、默拉皮火山与南海之间哲学轴线的白色立柱,是日惹最常被拍摄的地标,夜间亮灯时尤为上镜。'),
  ('Parangtritis Beach', 'en', 'Parangtritis Beach', 'A dramatic black-sand beach south of Yogyakarta, known for its sand dunes, sunset views and the legend of Nyai Roro Kidul, Queen of the Southern Sea. Strong currents make swimming unsafe.'),
  ('Parangtritis Beach', 'id', 'Pantai Parangtritis', 'Pantai pasir hitam dramatis di selatan Yogyakarta, terkenal akan gumuk pasir, sunset, dan legenda Nyai Roro Kidul. Arus kuat membuat berenang berbahaya.'),
  ('Parangtritis Beach', 'ko', '파랑트리티스 해변', '욕야카르타 남쪽의 인상적인 검은 모래 해변. 사구와 일몰, 남해의 여왕 냐이 로로 키둘 전설로 유명하다. 조류가 강해 수영은 위험하다.'),
  ('Parangtritis Beach', 'zh', '帕朗特里蒂斯海滩', '日惹以南壮观的黑沙海滩,以沙丘、日落和南海女王传说闻名。海流强劲,不宜游泳。'),
  ('Jomblang Cave', 'en', 'Jomblang Cave', 'A vertical sinkhole cave where visitors are lowered 60m by rope into an ancient sunken forest. Around midday a shaft of sunlight — the "light of heaven" — pierces the chamber.'),
  ('Jomblang Cave', 'id', 'Goa Jomblang', 'Gua sinkhole vertikal; pengunjung diturunkan 60m dengan tali ke hutan purba di dasar. Sekitar tengah hari "cahaya surga" menembus gua.'),
  ('Jomblang Cave', 'ko', '좀블랑 동굴', '수직 싱크홀 동굴. 밧줄로 60m 아래 고대 함몰림으로 내려간다. 정오 무렵 "천국의 빛"이라 불리는 햇살 기둥이 동굴 속을 관통한다.'),
  ('Jomblang Cave', 'zh', 'Jomblang天坑洞穴', '垂直天坑洞穴,游客用绳索下降60米进入古老的塌陷森林。正午前后一束"天堂之光"穿透洞穴。'),
  ('Kotagede Silver Quarter', 'en', 'Kotagede Silver Quarter', 'The historic former capital of the Mataram Sultanate, now famous for handcrafted silver. Silversmith workshops, heritage alleyways and the old royal cemetery make for an atmospheric wander.'),
  ('Kotagede Silver Quarter', 'id', 'Kotagede', 'Bekas ibu kota Kesultanan Mataram, kini terkenal akan kerajinan perak. Bengkel perak, gang-gang bersejarah, dan makam raja tua menciptakan suasana khas.'),
  ('Kotagede Silver Quarter', 'ko', '코타그데 은세공 거리', '마타람 술탄국의 옛 수도로 지금은 은세공으로 유명하다. 은세공 공방과 역사적인 골목길, 옛 왕실 묘지가 정취 있는 산책로를 이룬다.'),
  ('Kotagede Silver Quarter', 'zh', 'Kotagede银器区', '马塔兰苏丹国的旧都,如今以手工银器闻名。银匠作坊、历史小巷和古老的王室陵园营造出独特氛围。'),
  ('Museum Angkut', 'en', 'Museum Angkut', 'A large transport museum in highland Batu displaying hundreds of vintage cars, motorcycles and aircraft across elaborately themed zones — from old Batavia to Hollywood and Europe.'),
  ('Museum Angkut', 'id', 'Museum Angkut', 'Museum transportasi besar di Batu yang memamerkan ratusan mobil, motor, dan pesawat antik dalam zona bertema — dari Batavia lama hingga Hollywood dan Eropa.'),
  ('Museum Angkut', 'ko', '무세움 앙쿳 (교통 박물관)', '고지대 바투에 자리한 대형 교통 박물관. 옛 바타비아부터 할리우드·유럽까지 정교한 테마 구역에 수백 대의 클래식 자동차·오토바이·항공기를 전시한다.'),
  ('Museum Angkut', 'zh', '交通博物馆(Museum Angkut)', '位于高地巴图的大型交通博物馆,在精心设计的主题区(从老巴达维亚到好莱坞和欧洲)展出数百辆古董汽车、摩托车和飞机。'),
  ('Coban Rondo Waterfall', 'en', 'Coban Rondo Waterfall', 'An 84-metre waterfall in the cool Pujon highlands near Batu, reached by an easy paved path. A popular family spot with a hedge maze garden and forest picnic areas.'),
  ('Coban Rondo Waterfall', 'id', 'Air Terjun Coban Rondo', 'Air terjun setinggi 84m di dataran tinggi Pujon dekat Batu, dijangkau lewat jalur beraspal mudah. Tempat keluarga populer dengan taman labirin dan area piknik.'),
  ('Coban Rondo Waterfall', 'ko', '코반 론도 폭포', '바투 인근 시원한 푸존 고원의 84m 폭포. 포장된 평탄한 길로 접근하며, 미로 정원과 숲속 피크닉 구역을 갖춘 인기 가족 명소다.'),
  ('Coban Rondo Waterfall', 'zh', 'Coban Rondo瀑布', '巴图附近凉爽的Pujon高原上一座84米瀑布,沿平缓的铺装步道即可抵达。设有迷宫花园和林间野餐区,是热门的亲子去处。'),
  ('Alun-Alun Tugu Malang', 'en', 'Alun-Alun Tugu Malang', 'Malang''s elegant central square fronting the colonial city hall, with a circular lotus pond and heritage Dutch architecture — best enjoyed in the cool evening.'),
  ('Alun-Alun Tugu Malang', 'id', 'Alun-Alun Tugu Malang', 'Alun-alun pusat Malang di depan balai kota kolonial, dengan kolam teratai melingkar dan arsitektur Belanda bersejarah — paling nyaman saat sore.'),
  ('Alun-Alun Tugu Malang', 'ko', '알룬알룬 투구 (말랑 광장)', '식민지 시대 시청 앞에 자리한 말랑의 우아한 중앙 광장. 원형 연꽃 연못과 네덜란드풍 건축이 어우러져 선선한 저녁에 가장 좋다.'),
  ('Alun-Alun Tugu Malang', 'zh', '玛琅独立纪念广场', '玛琅市中心广场,正对殖民时期市政厅,有圆形荷花池和荷兰历史建筑,傍晚时分最为惬意。'),
  ('Jodipan Colorful Village', 'en', 'Jodipan Colorful Village', 'A riverside neighborhood reborn as a rainbow village — every house, alley and staircase painted in bright colours and murals, now one of Malang''s most Instagrammed spots.'),
  ('Jodipan Colorful Village', 'id', 'Kampung Warna-Warni Jodipan', 'Permukiman tepi sungai yang disulap jadi kampung pelangi — setiap rumah, gang, dan tangga dicat warna cerah dan mural, kini ikon foto Malang.'),
  ('Jodipan Colorful Village', 'ko', '조디판 무지개 마을', '강변 동네가 무지개 마을로 재탄생한 곳. 집과 골목, 계단마다 화사한 색과 벽화로 칠해져 말랑에서 가장 인기 있는 인증샷 명소가 되었다.'),
  ('Jodipan Colorful Village', 'zh', 'Jodipan彩虹村', '河畔社区改造成的彩虹村,每栋房屋、巷道和阶梯都涂上鲜艳色彩和壁画,如今是玛琅最上镜的打卡地之一。'),
  ('Batu Secret Zoo', 'en', 'Batu Secret Zoo', 'A modern, well-landscaped zoo within the Jatim Park 2 complex in Batu, with naturalistic enclosures, a large aquarium and rides — a top family day out in the Malang highlands.'),
  ('Batu Secret Zoo', 'id', 'Batu Secret Zoo', 'Kebun binatang modern di kompleks Jatim Park 2, Batu, dengan kandang naturalistik, akuarium besar, dan wahana — wisata keluarga favorit di dataran tinggi Malang.'),
  ('Batu Secret Zoo', 'ko', '바투 시크릿 주 (자팀파크2)', '바투의 자팀파크2 단지 안에 있는 현대식 동물원. 자연 친화적 사육장과 대형 아쿠아리움, 놀이기구를 갖춘 말랑 고원의 인기 가족 나들이 코스다.'),
  ('Batu Secret Zoo', 'zh', '巴图秘密动物园', '位于巴图Jatim Park 2园区内的现代化动物园,设有仿自然展区、大型水族馆和游乐设施,是玛琅高地热门的亲子去处。'),
  ('Selecta Recreational Park', 'en', 'Selecta Recreational Park', 'A historic hillside flower park (est. 1930) on Mount Arjuno''s slopes, with terraced gardens, a spring-fed pool, paddle boats and apple orchards in crisp highland air.'),
  ('Selecta Recreational Park', 'id', 'Taman Rekreasi Selecta', 'Taman bunga bersejarah (sejak 1930) di lereng Gunung Arjuno, dengan taman berundak, kolam mata air, perahu, dan kebun apel di udara sejuk.'),
  ('Selecta Recreational Park', 'ko', '슬렉타 휴양 공원', '아르주노 화산 기슭에 1930년 조성된 역사적인 꽃 공원. 계단식 화원과 샘물 수영장, 보트, 사과 과수원이 시원한 고원 공기 속에 펼쳐진다.'),
  ('Selecta Recreational Park', 'zh', 'Selecta游乐花园', '建于1930年的山坡花园,位于阿祖诺火山山麓,有梯田花园、泉水泳池、脚踏船和苹果园,高原空气清新。'),
  ('Balekambang Beach', 'en', 'Balekambang Beach', 'A scenic south-coast beach where a Hindu temple crowns an offshore islet reached by a footbridge — often likened to Bali''s Tanah Lot. Tide pools and dramatic sunsets reward the long drive.'),
  ('Balekambang Beach', 'id', 'Pantai Balekambang', 'Pantai pesisir selatan yang indah; pura Hindu berdiri di pulau kecil yang dihubungkan jembatan — sering disebut Tanah Lot-nya Jawa Timur.'),
  ('Balekambang Beach', 'ko', '발레캄방 해변', '앞바다 작은 섬 위에 힌두 사원이 있고 다리로 연결돼 "동자바의 타나롯"이라 불리는 남부 해안 해변. 조수 웅덩이와 극적인 일몰이 긴 여정을 보상한다.'),
  ('Balekambang Beach', 'zh', 'Balekambang海滩', '风景秀丽的南海岸海滩,印度教神庙坐落于近海小岛上,由步桥相连,常被称为"东爪哇的海神庙"。'),
  ('Coban Pelangi Waterfall', 'en', 'Coban Pelangi Waterfall', 'A 30m waterfall on the road to Mount Bromo, named for the rainbow that arcs through its mist on sunny mornings. A short forest trail leads down to the misty plunge pool.'),
  ('Coban Pelangi Waterfall', 'id', 'Air Terjun Coban Pelangi', 'Air terjun 30m di jalur menuju Gunung Bromo, dinamai pelangi yang muncul di kabutnya saat pagi cerah. Jalur hutan singkat menurun ke kolamnya.'),
  ('Coban Pelangi Waterfall', 'ko', '코반 펠랑이 폭포', '브로모 화산 가는 길에 있는 30m 폭포. 맑은 오전이면 물안개에 무지개가 떠 "무지개 폭포"로 불린다. 짧은 숲길을 내려가면 안개 자욱한 웅덩이가 나온다.'),
  ('Coban Pelangi Waterfall', 'zh', 'Coban Pelangi彩虹瀑布', '通往布罗莫火山途中的30米瀑布,因晴朗清晨水雾中常现彩虹而得名。沿短小的林间小径下行即达水潭。'),
  ('Tangkuban Perahu', 'en', 'Tangkuban Perahu', 'An active volcano north of Bandung whose huge "overturned boat" crater can be reached by car. Steaming sulphur vents, a turquoise crater lake and cool highland air at 2,000m.'),
  ('Tangkuban Perahu', 'id', 'Gunung Tangkuban Perahu', 'Gunung berapi aktif di utara Bandung dengan kawah raksasa yang bisa dicapai mobil. Uap belerang, danau kawah toska, dan udara sejuk di 2.000m.'),
  ('Tangkuban Perahu', 'ko', '탕쿠반 프라후 화산', '반둥 북쪽의 활화산으로, "뒤집힌 배" 모양의 거대한 분화구까지 차로 오를 수 있다. 유황 수증기와 청록빛 화구호, 해발 2,000m의 시원한 공기가 특징이다.'),
  ('Tangkuban Perahu', 'zh', '坦库班佩拉胡火山', '万隆以北的活火山,可驾车直达巨大的"覆舟"火山口。硫磺蒸汽、青绿色火口湖,海拔2000米空气清凉。'),
  ('Kawah Putih (White Crater)', 'en', 'Kawah Putih (White Crater)', 'A striking volcanic crater lake whose mineral water glows pale turquoise-white against bleached white earth — an otherworldly, much-photographed landscape in the highlands south of Bandung.'),
  ('Kawah Putih (White Crater)', 'id', 'Kawah Putih', 'Danau kawah vulkanik memukau dengan air mineral berwarna putih-toska di atas tanah putih — lanskap surreal yang sangat fotogenik di selatan Bandung.'),
  ('Kawah Putih (White Crater)', 'ko', '까와 뿌띠 (백색 화구호)', '광물질 물이 창백한 청록빛으로 빛나고 하얗게 탈색된 땅과 대비되는 화산 화구호. 반둥 남쪽 고원의 초현실적이고 사진 명소로 유명한 풍경이다.'),
  ('Kawah Putih (White Crater)', 'zh', '白色火山口湖(Kawah Putih)', '矿物质湖水呈淡青白色,衬托着漂白的白色土地,是万隆以南高地超现实而极上镜的景观。'),
  ('Gedung Sate', 'en', 'Gedung Sate', 'The landmark art-deco seat of the West Java government (1920), famous for the satay-skewer finial atop its central tower. Houses an interactive museum and a much-loved public lawn.'),
  ('Gedung Sate', 'id', 'Gedung Sate', 'Gedung pemerintahan Jawa Barat bergaya art-deco (1920), terkenal akan ornamen tusuk sate di puncak menaranya. Ada museum interaktif dan lapangan publik favorit.'),
  ('Gedung Sate', 'ko', '그둥 사테', '서자바 정부청사로 쓰이는 1920년 아르데코 양식 랜드마크. 중앙 첨탑 꼭대기의 사테 꼬치 모양 장식으로 유명하며, 체험형 박물관과 인기 잔디광장을 갖췄다.'),
  ('Gedung Sate', 'zh', '沙爹楼(Gedung Sate)', '西爪哇政府所在地,1920年的装饰艺术风格地标,因中央塔尖上的沙爹串状装饰得名,内设互动博物馆,前方草坪是人气聚集地。'),
  ('Floating Market Lembang', 'en', 'Floating Market Lembang', 'A lakeside market in cool Lembang where vendors serve Sundanese snacks and grilled food from wooden boats, paid for with special tokens — a relaxed, family-friendly outing north of Bandung.'),
  ('Floating Market Lembang', 'id', 'Floating Market Lembang', 'Pasar tepi danau di Lembang yang sejuk; pedagang menjual jajanan Sunda dari perahu kayu, dibayar dengan koin khusus — wisata keluarga santai di utara Bandung.'),
  ('Floating Market Lembang', 'ko', '플로팅 마켓 렘방', '시원한 렘방의 호숫가 시장. 상인들이 나무배에서 순다식 간식과 구이를 팔고 전용 토큰으로 결제한다. 반둥 북쪽의 여유로운 가족 나들이 코스다.'),
  ('Floating Market Lembang', 'zh', 'Lembang水上市场', '凉爽的Lembang湖畔市场,商贩在木船上售卖巽他小吃和烧烤,用专用代币付款,是万隆以北轻松的亲子去处。'),
  ('Dusun Bambu', 'en', 'Dusun Bambu', 'A bamboo-forest leisure park and eco-resort in the hills near Lembang, known for its lakeside "bird-nest" dining pods, flower gardens, boating and crisp mountain air.'),
  ('Dusun Bambu', 'id', 'Dusun Bambu', 'Taman rekreasi hutan bambu dan eco-resort di perbukitan dekat Lembang, terkenal akan saung "sarang burung" tepi danau, taman bunga, perahu, dan udara sejuk.'),
  ('Dusun Bambu', 'ko', '두순 밤부', '렘방 인근 언덕의 대나무 숲 레저 파크이자 에코 리조트. 호숫가 "새 둥지" 모양 식사 공간과 화원, 보트, 시원한 산 공기로 유명하다.'),
  ('Dusun Bambu', 'zh', '竹村(Dusun Bambu)', 'Lembang附近山中的竹林休闲园与生态度假区,以湖畔"鸟巢"式餐位、花园、划船和清凉山风闻名。'),
  ('Trans Studio Bandung', 'en', 'Trans Studio Bandung', 'A vast indoor theme park in central Bandung with around twenty rides, from a high-speed coaster to a 4D cinema — fully air-conditioned and a reliable rainy-day option for families.'),
  ('Trans Studio Bandung', 'id', 'Trans Studio Bandung', 'Taman hiburan indoor raksasa di pusat Bandung dengan sekitar dua puluh wahana, dari roller coaster cepat hingga bioskop 4D — ber-AC dan ideal saat hujan.'),
  ('Trans Studio Bandung', 'ko', '트랜스 스튜디오 반둥', '반둥 도심의 대형 실내 테마파크. 고속 롤러코스터부터 4D 영화관까지 약 20개의 어트랙션이 있고, 냉방이 되어 비 오는 날 가족 나들이에 좋다.'),
  ('Trans Studio Bandung', 'zh', '万隆Trans Studio室内乐园', '万隆市中心的大型室内主题乐园,约二十项游乐设施,从高速过山车到4D影院,全程空调,是雨天亲子的可靠之选。'),
  ('Farmhouse Lembang', 'en', 'Farmhouse Lembang', 'A European-style themed park in cool Lembang with a storybook "hobbit house", animal feeding, alpine cottages and costume rentals — a hugely popular photo-and-family destination.'),
  ('Farmhouse Lembang', 'id', 'Farmhouse Lembang', 'Taman bertema desa Eropa di Lembang yang sejuk, dengan "rumah hobbit" dongeng, memberi makan hewan, pondok alpine, dan sewa kostum — destinasi foto-keluarga populer.'),
  ('Farmhouse Lembang', 'ko', '팜하우스 렘방', '시원한 렘방의 유럽풍 테마 파크. 동화 같은 "호빗 하우스", 동물 먹이주기, 알프스풍 오두막, 의상 대여가 있어 사진·가족 명소로 큰 인기다.'),
  ('Farmhouse Lembang', 'zh', 'Lembang农舍乐园', '凉爽Lembang的欧式主题园,有童话"霍比特小屋"、动物喂食、阿尔卑斯小屋和服装租赁,是极受欢迎的拍照亲子目的地。'),
  ('Jalan Braga', 'en', 'Jalan Braga', 'A historic art-deco promenade in central Bandung — the city''s most fashionable street in colonial times — now a cobbled strip of vintage cafes, galleries and live-music bars.'),
  ('Jalan Braga', 'id', 'Jalan Braga', 'Pedestrian art-deco bersejarah di pusat Bandung — jalan paling modis pada masa kolonial — kini deretan kafe vintage, galeri, dan bar musik live.'),
  ('Jalan Braga', 'ko', '잘란 브라가', '"자바의 파리"라 불리던 반둥 도심의 역사적인 아르데코 거리. 식민지 시대 가장 세련된 거리였으며, 지금은 빈티지 카페·갤러리·라이브 음악 바가 늘어선 자갈길이다.'),
  ('Jalan Braga', 'zh', '布拉加街(Jalan Braga)', '万隆市中心历史悠久的装饰艺术步行街,殖民时期最时髦的街道,如今是布满复古咖啡馆、画廊和现场音乐酒吧的鹅卵石街。'),
  ('Maimun Palace', 'en', 'Maimun Palace', 'The opulent 1888 palace of the Sultanate of Deli, fusing Malay, Islamic, Mughal, Spanish and Italian design. Its yellow throne hall is the showpiece, with costume rental for photos.'),
  ('Maimun Palace', 'id', 'Istana Maimun', 'Istana mewah Kesultanan Deli (1888) yang memadukan gaya Melayu, Islam, Mughal, Spanyol, dan Italia. Balairung kuning kerajaan jadi sorotan, dengan sewa kostum.'),
  ('Maimun Palace', 'ko', '마이문 궁전', '1888년 델리 술탄국의 화려한 궁전. 말레이·이슬람·무굴·스페인·이탈리아 양식이 어우러졌다. 노란 알현실이 백미이며 사진용 의상 대여도 가능하다.'),
  ('Maimun Palace', 'zh', '马义孟皇宫', '德利苏丹国1888年的华丽宫殿,融合马来、伊斯兰、莫卧儿、西班牙和意大利风格。黄色御座大厅是亮点,可租服装拍照。'),
  ('Great Mosque of Medan (Al-Mashun)', 'en', 'Great Mosque of Medan (Al-Mashun)', 'Medan''s grand 1909 mosque commissioned by the Deli Sultanate, an octagonal masterpiece of Moroccan, Mughal and Spanish design with Italian marble and stained glass.'),
  ('Great Mosque of Medan (Al-Mashun)', 'id', 'Masjid Raya Al-Mashun', 'Masjid raya Medan (1909) yang dibangun Kesultanan Deli; mahakarya oktagonal bergaya Maroko, Mughal, dan Spanyol dengan marmer Italia dan kaca patri.'),
  ('Great Mosque of Medan (Al-Mashun)', 'ko', '메단 대모스크 (알마슌)', '델리 술탄국이 1909년 세운 메단의 대모스크. 모로코·무굴·스페인 양식이 어우러진 팔각형 걸작으로, 이탈리아 대리석과 스테인드글라스가 돋보인다.'),
  ('Great Mosque of Medan (Al-Mashun)', 'zh', '棉兰大清真寺(Al-Mashun)', '德利苏丹国1909年兴建的棉兰大清真寺,融合摩洛哥、莫卧儿和西班牙风格的八角形杰作,采用意大利大理石和彩绘玻璃。'),
  ('Lake Toba', 'en', 'Lake Toba', 'The largest volcanic lake on Earth, formed by a supervolcano eruption — a vast, cool highland caldera with Samosir Island at its centre, home to the Batak people and their distinctive culture.'),
  ('Lake Toba', 'id', 'Danau Toba', 'Danau vulkanik terbesar di dunia, terbentuk dari letusan supervolcano — kaldera sejuk yang luas dengan Pulau Samosir di tengahnya, tanah budaya Batak.'),
  ('Lake Toba', 'ko', '토바 호수', '초화산 분화로 형성된 세계 최대 화산호. 시원한 고원 칼데라 한가운데 사모시르 섬이 있으며, 바탁족과 그 독특한 문화의 본거지다.'),
  ('Lake Toba', 'zh', '多巴湖', '世界最大的火山湖,由超级火山喷发形成,是辽阔凉爽的高原破火山口,中心的萨摩西岛是巴塔克人及其独特文化的家园。'),
  ('Tjong A Fie Mansion', 'en', 'Tjong A Fie Mansion', 'The beautifully preserved 1900 mansion of Tjong A Fie, a Hakka Chinese merchant and philanthropist — a blend of Chinese, Malay and European design in Medan''s old Kesawan quarter.'),
  ('Tjong A Fie Mansion', 'id', 'Rumah Tjong A Fie', 'Rumah megah 1900 milik Tjong A Fie, saudagar dan dermawan Tionghoa Hakka — perpaduan gaya Tionghoa, Melayu, dan Eropa di kawasan tua Kesawan, Medan.'),
  ('Tjong A Fie Mansion', 'ko', '총아피 저택', '하카계 중국인 거상이자 자선가 총아피의 1900년 저택. 중국·말레이·유럽 양식이 어우러져 잘 보존됐으며, 메단의 옛 케사완 지구에 있다.'),
  ('Tjong A Fie Mansion', 'zh', '张阿辉故居', '客家华商兼慈善家张阿辉1900年的宅邸,保存完好,融合中式、马来和欧式风格,位于棉兰古老的Kesawan街区。'),
  ('Samosir Island', 'en', 'Samosir Island', 'A large island within Lake Toba and the cultural homeland of the Batak Toba people, dotted with traditional boat-roofed houses, royal stone tombs, hot springs and lakeside villages.'),
  ('Samosir Island', 'id', 'Pulau Samosir', 'Pulau besar di tengah Danau Toba dan tanah air budaya Batak Toba, dipenuhi rumah adat beratap perahu, makam batu raja, mata air panas, dan desa tepi danau.'),
  ('Samosir Island', 'ko', '사모시르 섬', '토바 호수 안의 큰 섬이자 바탁 토바족의 문화 본거지. 배 모양 지붕의 전통 가옥, 왕의 석조 무덤, 온천, 호숫가 마을이 곳곳에 있다.'),
  ('Samosir Island', 'zh', '萨摩西岛', '多巴湖中的大岛,巴塔克托巴人的文化故乡,遍布船形屋顶的传统民居、王室石墓、温泉和湖畔村落。'),
  ('Berastagi Highland', 'en', 'Berastagi Highland', 'A cool highland resort town in the Karo plateau, framed by the active Sibayak and Sinabung volcanoes — a base for dawn volcano hikes, hot springs and a colourful fruit-and-flower market.'),
  ('Berastagi Highland', 'id', 'Dataran Tinggi Berastagi', 'Kota peristirahatan sejuk di dataran tinggi Karo, dikelilingi gunung api Sibayak dan Sinabung — basis pendakian gunung, mata air panas, dan pasar buah-bunga.'),
  ('Berastagi Highland', 'ko', '브라스타기 고원', '카로 고원의 시원한 휴양 도시. 활화산 시바약·시나붕에 둘러싸여 새벽 화산 등반과 온천, 다채로운 과일·꽃 시장의 거점이 된다.'),
  ('Berastagi Highland', 'zh', 'Berastagi高原', 'Karo高原上凉爽的度假小镇,被活火山Sibayak和Sinabung环抱,是拂晓登火山、泡温泉和逛缤纷果花市场的据点。'),
  ('Graha Maria Annai Velangkanni', 'en', 'Graha Maria Annai Velangkanni', 'An extraordinary Catholic shrine built in Indo-Mughal temple style, dedicated to Our Lady of Velankanni — a seven-storey tower of arches and domes unlike any other church in Indonesia.'),
  ('Graha Maria Annai Velangkanni', 'id', 'Graha Maria Annai Velangkanni', 'Tempat ziarah Katolik luar biasa bergaya kuil Indo-Mughal, didedikasikan untuk Bunda Velankanni — menara tujuh lantai berlengkung dan berkubah yang unik.'),
  ('Graha Maria Annai Velangkanni', 'ko', '그라하 마리아 안나이 벨랑칸니', '인도-무굴 사원 양식으로 지은 독특한 가톨릭 성지. 벨랑칸니 성모를 모시며, 아치와 돔으로 이루어진 7층 탑이 인도네시아 어느 교회와도 다르다.'),
  ('Graha Maria Annai Velangkanni', 'zh', 'Annai Velangkanni圣母堂', '以印度-莫卧儿庙宇风格建造的奇特天主教圣所,供奉Velankanni圣母,七层拱顶塔楼,与印尼任何教堂都迥然不同。'),
  ('Rahmat International Wildlife Museum', 'en', 'Rahmat International Wildlife Museum', 'One of Asia''s largest wildlife and conservation museums, displaying hundreds of preserved animals from around the world in realistic habitat dioramas across two floors.'),
  ('Rahmat International Wildlife Museum', 'id', 'Museum Rahmat International Wildlife', 'Salah satu museum satwa dan konservasi terbesar di Asia, memamerkan ratusan hewan awetan dari seluruh dunia dalam diorama habitat realistis di dua lantai.'),
  ('Rahmat International Wildlife Museum', 'ko', '라흐맛 국제 야생동물 박물관', '아시아 최대급 야생동물·보전 박물관. 전 세계에서 온 수백 종의 박제 동물을 2개 층의 사실적인 서식지 디오라마로 전시한다.'),
  ('Rahmat International Wildlife Museum', 'zh', '拉赫马特国际野生动物博物馆', '亚洲最大的野生动物与保育博物馆之一,在两层楼中以逼真的栖息地立体场景展出数百种来自世界各地的标本动物。'),
  ('Bunaken National Marine Park', 'en', 'Bunaken National Marine Park', 'A legendary marine park off Manado famed for dramatic vertical coral walls, crystal visibility and extraordinary biodiversity — sea turtles, reef sharks and hundreds of coral and fish species.'),
  ('Bunaken National Marine Park', 'id', 'Taman Nasional Bunaken', 'Taman laut legendaris di lepas Manado, terkenal akan dinding karang vertikal dramatis, visibilitas jernih, dan biodiversitas luar biasa — penyu, hiu karang, dan ratusan spesies.'),
  ('Bunaken National Marine Park', 'ko', '부나켄 국립 해양공원', '마나도 앞바다의 전설적인 해양공원. 깎아지른 수직 산호벽과 맑은 시야, 놀라운 생물 다양성으로 유명하다. 바다거북·산호상어와 수백 종의 산호·어류를 볼 수 있다.'),
  ('Bunaken National Marine Park', 'zh', '布纳肯国家海洋公园', '美娜多外海的传奇海洋公园,以壮观的垂直珊瑚墙、清澈能见度和惊人的生物多样性闻名,有海龟、礁鲨及数百种珊瑚和鱼类。'),
  ('Mount Lokon', 'en', 'Mount Lokon', 'An active volcano rising above the flower city of Tomohon, with a constantly smoking crater. A pre-dawn hike rewards climbers with sweeping views over the highlands and the Celebes Sea.'),
  ('Mount Lokon', 'id', 'Gunung Lokon', 'Gunung berapi aktif di atas kota bunga Tomohon, dengan kawah yang terus berasap. Pendakian dini hari memberi panorama luas dataran tinggi dan Laut Sulawesi.'),
  ('Mount Lokon', 'ko', '로콘 화산', '꽃의 도시 토모혼 위로 솟은 활화산으로 분화구에서 늘 연기가 난다. 새벽 등반에 나서면 고원과 술라웨시 해를 굽어보는 탁 트인 전망이 보상으로 주어진다.'),
  ('Mount Lokon', 'zh', '洛孔火山', '矗立在花城多莫洪之上的活火山,火山口持续冒烟。拂晓登山可俯瞰高原与西里伯斯海的开阔全景。'),
  ('Tangkoko Nature Reserve', 'en', 'Tangkoko Nature Reserve', 'A coastal rainforest reserve near Bitung, world-famous for the tiny wide-eyed tarsier and endemic black-crested macaques. Dawn and dusk guided treks offer some of Sulawesi''s best wildlife viewing.'),
  ('Tangkoko Nature Reserve', 'id', 'Cagar Alam Tangkoko', 'Cagar alam hutan pesisir dekat Bitung, terkenal akan tarsius mungil bermata besar dan monyet hitam endemik. Trek berpemandu saat fajar dan senja untuk melihat satwa.'),
  ('Tangkoko Nature Reserve', 'ko', '탕코코 자연보호구역', '비퉁 인근 해안 우림 보호구역. 눈이 큰 작은 안경원숭이(타르시어)와 고유종 검은볏마카크로 세계적으로 유명하다. 새벽·해질녘 가이드 트레킹이 압권이다.'),
  ('Tangkoko Nature Reserve', 'zh', 'Tangkoko自然保护区', '比通附近的海岸雨林保护区,以大眼睛的小眼镜猴和特有的黑冠猕猴闻名于世。黎明和黄昏的向导徒步是苏拉威西最佳的观野生动物体验之一。'),
  ('Christ Blessing Statue', 'en', 'Christ Blessing Statue', 'A towering 50-metre statue of a forward-leaning, "flying" Jesus on a hilltop above Manado — among the tallest Christ statues in Asia and a striking sunset viewpoint over the city.'),
  ('Christ Blessing Statue', 'id', 'Patung Yesus Memberkati', 'Patung Yesus setinggi 50m yang condong ke depan seakan terbang, di atas bukit Manado — salah satu patung Kristus tertinggi di Asia dan titik sunset memukau.'),
  ('Christ Blessing Statue', 'ko', '예수 강복상', '마나도가 내려다보이는 언덕 위, 날아가듯 앞으로 기운 50m 높이의 예수상. 아시아에서 가장 높은 예수상 중 하나로, 도시 너머 일몰 전망이 인상적이다.'),
  ('Christ Blessing Statue', 'zh', '耶稣祝福像', '美娜多山顶上一座50米高、前倾如飞翔的耶稣像,是亚洲最高的耶稣像之一,也是俯瞰全城的绝佳日落观景点。'),
  ('Lake Linow', 'en', 'Lake Linow', 'A sulphur crater lake near Tomohon whose surface shifts between turquoise, green and amber depending on light and mineral content, ringed by viewpoint cafes and steaming fumaroles.'),
  ('Lake Linow', 'id', 'Danau Linow', 'Danau kawah belerang dekat Tomohon yang berganti warna antara toska, hijau, dan kuning tergantung cahaya dan kandungan mineral, dikelilingi kafe dan fumarol berasap.'),
  ('Lake Linow', 'ko', '리노우 호수', '토모혼 인근 유황 화구호. 빛과 광물 함량에 따라 청록·초록·호박빛으로 수면 색이 변한다. 전망 카페와 김 오르는 분기공이 호수를 둘러싼다.'),
  ('Lake Linow', 'zh', '利诺湖', '多莫洪附近的硫磺火口湖,湖面随光线和矿物含量在青绿、绿色与琥珀色间变幻,周围有观景咖啡馆和冒烟的喷气孔。'),
  ('Bukit Kasih Kanonang', 'en', 'Bukit Kasih Kanonang', 'A volcanic "Hill of Love" symbolising religious tolerance, crowned by five houses of worship for Indonesia''s major faiths and a tall hilltop cross reached by a long sulphur-scented stairway.'),
  ('Bukit Kasih Kanonang', 'id', 'Bukit Kasih Kanonang', 'Bukit vulkanik "kasih" simbol toleransi beragama, dimahkotai lima rumah ibadah untuk agama besar Indonesia dan salib tinggi yang dicapai lewat tangga panjang.'),
  ('Bukit Kasih Kanonang', 'ko', '부킷 카시 카노낭', '종교적 관용을 상징하는 화산 "사랑의 언덕". 인도네시아 주요 종교의 다섯 예배소와 긴 계단 끝의 높은 십자가가 정상을 장식하고, 주변엔 유황 분기공이 김을 뿜는다.'),
  ('Bukit Kasih Kanonang', 'zh', 'Kanonang爱之丘', '象征宗教宽容的火山"爱之丘",山顶设有印尼五大宗教的礼拜场所,以及沿长阶梯登上的高大十字架,附近硫磺喷气孔冒烟。'),
  ('Siladen Island', 'en', 'Siladen Island', 'A tiny, tranquil white-sand island within Bunaken National Park, ringed by a shallow coral reef ideal for snorkelling straight from the beach — a quieter alternative to Bunaken itself.'),
  ('Siladen Island', 'id', 'Pulau Siladen', 'Pulau pasir putih kecil nan tenang di Taman Nasional Bunaken, dikelilingi terumbu dangkal yang ideal untuk snorkeling dari pantai — alternatif lebih sepi dari Bunaken.'),
  ('Siladen Island', 'ko', '실라덴 섬', '부나켄 국립공원 안의 작고 고요한 백사장 섬. 해변에서 바로 스노클링하기 좋은 얕은 산호초로 둘러싸여, 부나켄보다 한적한 대안이다.'),
  ('Siladen Island', 'zh', '西拉登岛', '布纳肯国家公园内一座宁静的白沙小岛,周围浅珊瑚礁适合从沙滩直接浮潜,是比布纳肯更清静的选择。'),
  ('Mount Mahawu', 'en', 'Mount Mahawu', 'An easily climbed volcano near Tomohon: a short staircase leads to the crater rim, where a green crater lake and panoramic views toward Mount Lokon and the Celebes Sea await.'),
  ('Mount Mahawu', 'id', 'Gunung Mahawu', 'Gunung berapi yang mudah didaki dekat Tomohon: tangga singkat menuju bibir kawah dengan danau kawah hijau dan panorama ke Gunung Lokon serta Laut Sulawesi.'),
  ('Mount Mahawu', 'ko', '마하우 화산', '토모혼 인근의 오르기 쉬운 화산. 짧은 계단을 오르면 초록빛 화구호가 있는 분화구 가장자리에 닿고, 로콘 화산과 술라웨시 해로 향하는 파노라마가 펼쳐진다.'),
  ('Mount Mahawu', 'zh', '马哈乌火山', '多莫洪附近易于攀登的火山,沿短阶梯即达火山口边缘,可见绿色火口湖以及通往洛孔火山和西里伯斯海的全景。'),
  ('Bogor Botanical Gardens', 'en', 'Bogor Botanical Gardens', 'A historic 87-hectare botanical garden founded in 1817, home to over 15,000 plant species, towering rainforest giants, an orchid house and lily ponds — wrapped around the Bogor Presidential Palace.'),
  ('Bogor Botanical Gardens', 'id', 'Kebun Raya Bogor', 'Kebun raya bersejarah seluas 87 hektar (didirikan 1817), menampung 15.000+ spesies tanaman, pohon hutan raksasa, rumah anggrek, dan kolam — mengelilingi Istana Bogor.'),
  ('Bogor Botanical Gardens', 'ko', '보고르 식물원', '1817년 조성된 87헥타르 규모의 역사적 식물원. 1만 5천여 종의 식물과 거대한 우림 나무, 난초 온실, 수련 연못을 갖췄으며 보고르 대통령궁을 둘러싸고 있다.'),
  ('Bogor Botanical Gardens', 'zh', '茂物植物园', '建于1817年、占地87公顷的历史植物园,拥有逾15000种植物、参天雨林巨木、兰花温室和睡莲池,环绕着茂物总统府。'),
  ('Taman Safari Indonesia', 'en', 'Taman Safari Indonesia', 'A drive-through safari park in the cool Puncak highlands where lions, elephants and zebras roam around your car, combined with a walking zoo, animal shows and rides — a top family destination.'),
  ('Taman Safari Indonesia', 'id', 'Taman Safari Indonesia', 'Taman safari berkendara di dataran tinggi Puncak yang sejuk; singa, gajah, dan zebra berkeliaran di sekitar mobil, plus kebun binatang jalan kaki, atraksi, dan wahana.'),
  ('Taman Safari Indonesia', 'ko', '따만 사파리 인도네시아', '시원한 푼짝 고원의 드라이브스루 사파리. 사자·코끼리·얼룩말이 차 주변을 자유로이 다니며, 도보 동물원과 동물 쇼·놀이기구까지 갖춘 인기 가족 명소다.'),
  ('Taman Safari Indonesia', 'zh', '印度尼西亚野生动物园', '位于凉爽Puncak高地的自驾式野生动物园,狮子、大象和斑马在车旁自由漫步,另有步行动物园、动物表演和游乐设施,是热门亲子目的地。'),
  ('Bogor Palace', 'en', 'Bogor Palace', 'A graceful 18th-century colonial state palace set within the Botanical Gardens, best known for the herd of spotted deer grazing its lawns — still used for official state occasions.'),
  ('Bogor Palace', 'id', 'Istana Bogor', 'Istana negara kolonial abad ke-18 yang anggun di dalam Kebun Raya, terkenal akan kawanan rusa totol di halamannya — masih dipakai untuk acara kenegaraan.'),
  ('Bogor Palace', 'ko', '보고르 궁전', '식물원 안에 자리한 우아한 18세기 식민지 시대 영빈관. 잔디밭에서 풀을 뜯는 꽃사슴 무리로 유명하며, 지금도 국가 공식 행사에 쓰인다.'),
  ('Bogor Palace', 'zh', '茂物宫', '坐落于植物园内的优雅18世纪殖民时期国宾馆,以草坪上成群吃草的花鹿闻名,至今仍用于国家正式场合。'),
  ('Gunung Pancar Hot Springs', 'en', 'Gunung Pancar Hot Springs', 'A hillside pine forest park with natural hot-spring bathing pools, shady photogenic groves and camping grounds — a relaxed nature escape in the hills northeast of Bogor.'),
  ('Gunung Pancar Hot Springs', 'id', 'Pemandian Air Panas Gunung Pancar', 'Taman hutan pinus dengan kolam pemandian air panas alami, rimbun pohon pinus yang fotogenik, dan area kemah — pelarian alam santai di timur laut Bogor.'),
  ('Gunung Pancar Hot Springs', 'ko', '구눙 판짜르 온천', '천연 온천탕이 있는 언덕 소나무 숲 공원. 그늘진 사진 명소 소나무 숲과 캠핑장을 갖춘, 보고르 북동쪽 언덕의 여유로운 자연 휴식처다.'),
  ('Gunung Pancar Hot Springs', 'zh', 'Gunung Pancar温泉', '山坡松林公园,设有天然温泉浴池、上镜的浓荫松林和露营地,是茂物东北山间惬意的自然胜地。'),
  ('Puncak Pass', 'en', 'Puncak Pass', 'A scenic highland mountain pass between Bogor and Cianjur, blanketed by the emerald Gunung Mas tea plantations — a cool-air retreat for tea-estate walks, paragliding and panoramic valley views.'),
  ('Puncak Pass', 'id', 'Puncak Pass', 'Jalur pegunungan indah antara Bogor dan Cianjur, berselimut kebun teh Gunung Mas yang hijau — pelarian sejuk untuk jalan-jalan kebun teh, paralayang, dan panorama lembah.'),
  ('Puncak Pass', 'ko', '푼짝 고개', '보고르와 찌안주르 사이의 경치 좋은 고원 고갯길. 에메랄드빛 구눙 마스 차밭이 펼쳐져, 차밭 산책과 패러글라이딩, 계곡 파노라마를 즐기는 시원한 휴양지다.'),
  ('Puncak Pass', 'zh', 'Puncak山口', '茂物与展玉之间风景优美的高原山口,被翠绿的Gunung Mas茶园覆盖,是茶园漫步、滑翔伞和山谷全景的清凉胜地。'),
  ('Curug Cilember Waterfall', 'en', 'Curug Cilember Waterfall', 'A chain of seven tiered waterfalls cascading through cool Puncak pine forest, with the easily-reached lowest fall, a butterfly conservatory and forest camping — a refreshing highland nature spot.'),
  ('Curug Cilember Waterfall', 'id', 'Curug Cilember', 'Rangkaian tujuh air terjun bertingkat di hutan pinus Puncak yang sejuk, dengan air terjun terbawah yang mudah dijangkau, konservasi kupu-kupu, dan area kemah.'),
  ('Curug Cilember Waterfall', 'ko', '쭈룽 찔름버 폭포', '시원한 푼짝 소나무 숲을 흐르는 7단 폭포 군. 가장 아래 폭포는 쉽게 닿고, 나비 보존원과 숲 캠핑장도 있는 상쾌한 고원 자연 명소다.'),
  ('Curug Cilember Waterfall', 'zh', 'Cilember七叠瀑布', '在凉爽的Puncak松林中层层跌落的七叠瀑布,最下层瀑布步行可达,另有蝴蝶保育园和林间露营,是清新的高原自然景点。'),
  ('The Jungle Waterpark', 'en', 'The Jungle Waterpark', 'A large family water park on Bogor''s southern edge with wave pools, twisting slides, a lazy river and a 4D cinema, set against a backdrop of green mountains.'),
  ('The Jungle Waterpark', 'id', 'The Jungle Waterpark', 'Taman air keluarga besar di selatan Bogor dengan kolam ombak, seluncuran berkelok, kolam arus, dan bioskop 4D, berlatar pegunungan hijau.'),
  ('The Jungle Waterpark', 'ko', '더 정글 워터파크', '보고르 남쪽의 대형 가족 워터파크. 파도풀과 굽이치는 슬라이드, 유수풀, 4D 영화관을 갖췄으며 푸른 산을 배경으로 한다.'),
  ('The Jungle Waterpark', 'zh', '丛林水上乐园', '茂物南缘的大型亲子水上乐园,有造浪池、回旋滑梯、漂流河和4D影院,以青翠群山为背景。'),
  ('Devoyage Bogor', 'en', 'Devoyage Bogor', 'A photo-themed park recreating miniature world destinations — whitewashed Santorini lanes, Moroccan doorways and Japanese streets — designed end to end as an Instagram playground.'),
  ('Devoyage Bogor', 'id', 'Devoyage Bogor', 'Taman bertema foto yang menghadirkan miniatur destinasi dunia — lorong Santorini putih, pintu Maroko, dan jalan Jepang — dirancang penuh untuk Instagram.'),
  ('Devoyage Bogor', 'ko', '드보야지 보고르', '세계 명소를 미니어처로 재현한 포토 테마 파크. 새하얀 산토리니 골목, 모로코풍 문, 일본식 거리까지 처음부터 끝까지 인스타그램을 위해 꾸며졌다.'),
  ('Devoyage Bogor', 'zh', 'Devoyage Bogor', '以拍照为主题的乐园,微缩重现世界各地景观——洁白的圣托里尼小巷、摩洛哥门廊和日式街道,从头到尾为Instagram打造。')
) as t(spot_name, lang, name, description) on t.spot_name = new_spots.name
on conflict (spot_id, lang) do nothing;
